### ISSUE TITLE
Inconsistency: scripting.registerContentScripts and contentScripts.register

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#125]
Currently Chromium and Firefox have a different API for registering contentScripts.

Firefox was the first to implement `browser.contentScripts.register`. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register.

Chromium added / is about to add `chrome.scripting.registerContentScripts`. See:
https://developer.chrome.com/docs/extensions/mv3/content_scripts/ and 
https://bugs.chromium.org/p/chromium/issues/detail?id=1054624

Since these APIs seem to do about the same thing, we should find ways to bring them closer together / work towards a single API design.

**Comment by Rob--W** [comment]
Firefox will deprecate the `contentScripts` API in favor of the scripting API namespace.

One design issue with `contentScripts.register` is that the lifetime of the script is tied to the lifetime of the calling page (e.g. background page). The `scripting` API fixes that.

**Comment by carlosjeurissen** [comment]
Thanks so much for the update Rob! Is Firefox considering supporting this in MV2 as well? Or are there any specific reasons either technical or others to restrict it to MV3?

**Comment by Rob--W** [comment]
We're currently developing "new" features behind a flag for MV3, but if the API is mature I wouldn't rule out the possibility of making it available under MV2 too.

**Comment by Rob--W** [comment]
I believe that this issue has been resolved. We may file new issues for the `scripting` API in the future, but the question asked here has been answered.
