### ISSUE TITLE
Proposal: add `runtime.openShortcutsPage`

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#126]
This has been proposed on CrBug and the chrome extensions forum:
https://groups.google.com/a/chromium.org/g/extension-api-reviews/c/4Odm0D9FR_E
https://bugs.chromium.org/p/chromium/issues/detail?id=1173375

There is a need to open the "keyboard shortcuts" settings page programmatically just like you currently can open the options page using `browser.runtime.openOptionsPage`.

Originally, `browser.runtime.openShortcutsPage` has been proposed. Alternatively we could go for `browser.runtime.openCommandsPage` or `browser.commands.openOptionsPage`.

**Comment by oliverdunk** [comment]
Thanks for opening this! I didn't see any movement on my post in the Google group but hopefully we see some now.

**Comment by Rob--W** [comment]
Closing in favor of #310 because that has more recent discussions.
