### ISSUE TITLE
Proposal: keep `browser_action` and do not rename it to `action`

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#127]
A proposal was made and implemented in Chromium to rename `browser_action` to `action` in mv3. As the `action` is pretty much equivalent to `browser_action` it seems the name change thus doesn't make much sense.

My proposal here is to not rename `browser_action` and if needed treat `action` as alternative name for the API at least for mv3. This would allow other vendors to keep supporting `page_action` and would also prevent confusion with `sidebar_action`.

**Comment by xeenon** [comment]
I think the rename makes sense. Safari treats `browser_action` and `page_action` as the same in v2 already.

**Comment by carlosjeurissen** [comment]
Since `action` is pretty much established and accepted, this proposal does not make sense anymore. Closing this as a result.
