### ISSUE TITLE
Admin: Should we skip 11/25 due to proximity to US Thanksgiving?

### ISSUE THREAD

**Issue by dotproto** [hober/web-extensions#130]
The meeting after next is scheduled to occur on 11/25, just two days before Thanksgiving in the US. This is close enough that my company is giving us Thursday the 25th and Friday the 26th off.

I'm curious if other US based or affiliated attendees plan to be out on the 25th. If we have a couple members that plan to be out, I think it may be best to skip.

**Comment by xeenon** [comment]
We talked about this a bit on the Matrix chat and decided to cancel this one and the one close to Christmas.

https://www.w3.org/events/meetings/f13adee3-d80c-4348-bc2a-64e006b0db4a/20211125T150000
https://www.w3.org/events/meetings/f13adee3-d80c-4348-bc2a-64e006b0db4a/20211223T150000
