### ISSUE TITLE
Setting up of Agenda for WECG meeting [Next : 20th Jan 2022]

### ISSUE THREAD

**Issue by mukul-p** [hober/web-extensions#144]
Please add topics and expected time-box for each for the next meeting(s).

This issue should be closed at least two days before the actual meeting

**Comment by dotproto** [comment]
In our last public meeting I floated some ideas on potential changes to our meeting process. I've written up these ideas in a bit more detail and shared them in issue #145.

If there's meaningful discussion on that issue, we may want discuss it in the next session.

**Comment by oliverdunk** [comment]
I'm curious about how each browser vendor feels on two APIs in particular. I've opened https://github.com/w3c/webextensions/issues/146. It may be possible to handle them asynchronously but also suggesting for the agenda.

**Comment by dotproto** [comment]
Closing this issue as the 2022-01-20 meeting has concluded.
