### ISSUE TITLE
Clarify browser vendor positions on APIs in MV3

### ISSUE THREAD

**Issue by oliverdunk** [hober/web-extensions#146]
There are a few API's that I'd love to know each browser vendor's thoughts on:

- The MV3 storage.session API recently introduced by Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1185226
- Cross-extension messaging (runtime.onMessageExternal) in MV3 extensions

Opening this issue with both so I can suggest these for the agenda.

**Comment by zombie** [comment]
We plan to implement the `storage.session` API, for similar reason, though we will likely use the (now standard) [structured clone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) algorithm for both ergonomic and performance reasons (IMO it's pure win compared to JSON).

I'm not aware of any changes related to `runtime.onMessageExternal` for MV3, you would need to ask a more specific question.

**Comment by zombie** [comment]
(also nit: keeping issues focused on one topic makes it easier to triage, discuss and eventually resolve)

**Comment by oliverdunk** [comment]
> I'm not aware of any changes related to runtime.onMessageExternal for MV3

Ok, I think that's all we need for now to be honest. I just wanted to make sure it wasn't going away.

> (also nit: keeping issues focused on one topic makes it easier to triage, discuss and eventually resolve)

Totally fair! I can break things like this down slightly further in the future.

Thanks for replying here.

**Comment by oliverdunk** [comment]
Notes from the 2022-01-20 meeting:

>  * [oliver] Is storage.session API going to be adopted by other browsers? Saw comments about structured cloning, can that be used to store non-JSON data?
>  * [tomislav] API is going to be the same. Structured cloning may be an option.
>  * [rob] We haven't started on implementation yet, but broadly it makes sense to have a consistent object serialization format across storage apis
>  * [jessie] (on behalf of Apple) Policy to not talk about unreleased APIs. The currently released MV3 API in Safari doesn't have storage.session.
>  * [oliver] cross-extension messaging: will runtime.sendMessage to message other extensions continue to be supported?
>  * [simeon] On Chrome this API should continue to work as expected. If it doesn't, that's a bug and we should fix it.
>  * [rob] On Firefox side, no plans to remove it either.
>  * [jessie] In Safari this API is not implemented.

With that in mind I'm going to close this issue, since I mostly opened to have a link for the agenda.
