### ISSUE TITLE
it's impossible to integrate google analytics with MV3

### ISSUE THREAD

**Issue by markon1** [hober/web-extensions#152]
it's impossible to integrate google analytics with MV3, since it won't allow this in `manifest.json`:
`"content_security_policy": { "extension_pages": "script-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://js.refiner.io; object-src 'self'" }`

**Comment by xeenon** [comment]
This is by design and we support blocking remote code at Apple.

**Comment by carlosjeurissen** [comment]
Would there be a way for the Google Analytics team to provide a version of the analytics script which can be added directly to the extension source so we do not have to deal with the remote code restriction?

**Comment by ghostwords** [comment]
The workaround suggested in [today's meeting](https://github.com/w3c/webextensions/tree/main/_minutes):

https://blog.mozilla.org/addons/2016/05/31/using-google-analytics-in-extensions/

**Comment by Rob--W** [comment]
Meeting notes will be published at https://github.com/w3c/webextensions/blob/main/_minutes/2022-02-03-wecg.md.

**Comment by Rob--W** [comment]
I'm closing this issue because there is universal consensus that this is the desired behavior.
