### ISSUE TITLE
geolocation API is not working with service workers

### ISSUE THREAD

**Issue by markon1** [hober/web-extensions#153]
geolocation API is not working with service workers, since they're not regular HTML pages like background was in MV2

**Comment by dotproto** [comment]
It looks like you've already highlighted this concern in [this comment](https://github.com/w3c/webextensions/issues/72#issuecomment-974897052) on #72. Additional context on the decision not to expose geolocation in service workers can be found in w3c/ServiceWorker#745 and it appears additional geolocation discussion is occuring in w3c/geolocation#214.

**Comment by ghostwords** [comment]
Also, the relevant crbug: [Issue 1279641: Geolocation API is not available to extension service workers](https://bugs.chromium.org/p/chromium/issues/detail?id=1279641).

I don't think it makes sense to point to discussions regarding **website** service workers as the explanation for something that is being broken by Google in **browser extensions**.
