### ISSUE TITLE
Allow users to decline host permissions at install time

### ISSUE THREAD

**Issue by bershanskiy** [hober/web-extensions#161]
During Chrome Developer Summit 2020 (which took place in December 2020), Simeon Vincent announced this in ["Extensions patterns for Manifest V3"](https://youtu.be/kybyYwu9Mpw?t=296):
> In a future release, Chrome will no longer grant declared host permissions at installation time by default.

Is this change still planned? As an end-user, I really would like to see this come to life. However, as a developer, I would like to know how to prepare for this change in advance.

**Comment by Rob--W** [comment]
@dotproto ^

**Comment by dotproto** [comment]
Yes, we are still pursuing this change in Chrome. As stated in that talk, this change will apply to both Manifest V2 and Manifest V3 extensions.

[Issue 1289519](https://crbug.com/1289519) is a feature request to provide extension developers with a way to emulate this change. When we have more to share, we will publish updates to developer.chrome.com. Keep an eye on our What's New page and watch the extensions tags for relevant blog post ([page](https://developer.chrome.com/tags/extensions), [feed](https://developer.chrome.com/feeds/extensions.xml)).
