### ISSUE TITLE
Proposal: provide information to extension via `ExtensionSettings` Enterprise Policy settings 

### ISSUE THREAD

**Issue by twschiller** [hober/web-extensions#174]
Context: 
- Chromium browsers and Firefox enable Enterprise IT departments to set policies via Group Policies (Windows) and similar mechanisms
- As an IT administrator, I want to configure the extension experience without user authentication (or prior to the user authenticating). For example:
   1. Restricting features
   2. Applying branding/co-branding/theme
   3. Setting the tenant/hostname for IDP (e.g. for an on-premise/VPC IDP)

Proposal:
- Add a `configuration` key to ExtensionSettings that accepts a custom JSON payload
- Add a `browser.runtime.getConfiguredPolicy` method to retrieve the configuration payload

Alternative:
- Expose the runtime_allowed_hosts to the extension so that the extension can search well-known URL patterns to fetch the information from

Workarounds (not suitable/practical):
- Provide different build of the extension for each enterprise customer
- On Chromium, request the [identity.email permission](https://developer.chrome.com/docs/extensions/reference/identity/#type-ProfileUserInfo), get the email, and phone home to a central service to determine the configuration to apply

Related Information:
- https://chromeenterprise.google/policies/?policy=ExtensionSettings
- https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide
- https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

**Comment by dotproto** [comment]
Are you familiar with `storage.managed` ([dcc](https://developer.chrome.com/docs/extensions/reference/storage/#property-managed), [mdn](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed))? I think it provides the capabilities that you're looking for. The following description comes from MDN (emphasis mine).

> A [`storage.StorageArea`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea) object that represents the `managed` storage area. **Items in `managed` storage are set by the domain administrator or other native applications installed on user's computer, and are read-only for the extension.** Trying to modify this storage area results in an error.

**Comment by twschiller** [comment]
Thanks @dotproto that looks exactly like what we need. Now to figure out how to actually provide the values. Both the Chrome and MDN documentation for enterprise extension management is quite hard to grok

**Comment by dotproto** [comment]
To be honest I’m surprised how hard it is to find useful reference docs for this. After more searching than I’m comfortable with, I found https://www.chromium.org/administrators/configuring-policy-for-extensions/ for the Chromium side. This page describes the specific locations where the extensions’s policy (the values exposed in managed storage) must be set per OS.

 I haven’t found an equivalent resource for Firefox.

**Comment by ghostwords** [comment]
>To be honest I’m surprised how hard it is to find useful reference docs for this

Managed storage is a complete mess. You may find useful [this Privacy Badger admin configuration guide](https://github.com/EFForg/privacybadger/blob/master/doc/admin-deployment.md) I've been cobbling together from user feedback.

Beyond missing/confusing docs, we also have to deal with bugs like [Chromium's apparent inability to consistently ingest extension policy values](https://github.com/EFForg/privacybadger/issues/2832) in time for a force-installed extension's first run in a new profile.

**Comment by zombie** [comment]
@twschiller If I'm understanding your question, the instructions for Firefox should be here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

Please let me know if something is still missing or unclear (or better yet, open an issue/PR on github directly).
