### ISSUE TITLE
Label naming for issues where consensus has been achieved

### ISSUE THREAD

**Issue by Rob--W** [hober/web-extensions#205]
The number of issues in this tracker is growing, and so is the comparatively smaller number of issues where cross-browser consensus has been achieved, the success stories of our group. We need a label to track issues with broad agreements.

Some has suggested "fixed" or "complete", but I'd like to see a less generic name that more accurately reflects broad approval, even if the changes themselves have not actually been implemented/shipped yet.

We don't necessarily need to track issues that have been rejected (there is already a wontfix label for that).

**Comment by xeenon** [comment]
I think we can use the new `accepted`, `rejected`, or `implemented` labels mentioned in #244 to track consensus across all the browsers. When more than one browser accepts or implements it can be considered for inclusion.
