### ISSUE TITLE
Agenda discussion for public meeting on 2022-05-12

### ISSUE THREAD

**Issue by oliverdunk** [hober/web-extensions#209]
Please comment on this issue to add topics for our next meeting. The agenda will be finalized two days before the actual meeting and migrated to our [meeting notes doc](https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit).

**Current topic list**

- @oliverdunk, #208 
- @felipeerias, #162

**Comment by felipeerias** [comment]
I would like to add https://github.com/w3c/webextensions/issues/162 (disable individual static rules in DRN) to the agenda.

**Comment by oliverdunk** [comment]
Closing this ahead of the meeting later today, issues have been moved over to the meeting notes.
