### ISSUE TITLE
Support browserAction.setBadgeTextColor()

### ISSUE THREAD

**Issue by AidanWelch** [hober/web-extensions#216]
Firefox has supported setBadgeTextColor() since 2018, but no other browsers currently support it.  Standardizing a relatively minor function that would improve the customization of extension badges seems beneficial.

**Comment by carlosjeurissen** [comment]
In addition to `browserAction.setBadgeTextColor`, Firefox also implemented `browserAction.getBadgeTextColor`. And for compatibility with manifest v3, `action.setBadgeTextColor` and `action.getBadgeTextColor` should be considered.

Some additional background can be found in the bugzilla issue report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1424620

I suggest to first discuss how the foreground color is determined by browsers, see if we can find alignment on this field as well.

**Comment by xeenon** [comment]
We should keep dark mode in mind here. We likely would need to let the caller set a color for each mode so it can look right if/when the user switches their UI between light and dark modes.

**Comment by hanguokai** [comment]
I would like to know what is the default BadgeTextColor and BadgeBackgroundColor in different browsers (if developers don't set them).

On Chrome, the default is White/Blue. And Edge's was the same as Chrome in the past. But recently Edge changed to White/Red.

**Comment by hanguokai** [comment]
Here is a related chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1337783) about badge's color contrast. The problem is that, in some cases, the badge text color chosen by the browser is unreadable, especially the badge is very small. Maybe some color experts can help solve it.

**Comment by dotproto** [comment]
Chrome is open to exposing `action.setBadgeTextColor()` but don't have immediate plans to do so. We will be using [crbug.com/1337783](https://crbug.com/1337783) to track this feature request.

**Comment by carlosjeurissen** [comment]
There is further progress on this on https://crbug.com/1363445

**Comment by hanguokai** [comment]
Close this issue. Because Chrome has implemented `action.setBadgeTextColor()` and `action.getBadgeTextColor()`. They are available since Chrome 110.
