### ISSUE TITLE
Extensions Store Badge (get the extension button)

### ISSUE THREAD

**Issue by hanguokai** [hober/web-extensions#224]
![get-the-addon](https://user-images.githubusercontent.com/776467/172134802-013d3af2-00fa-45a4-94f7-a772ff29fab0.png) ![get-the-extension](https://user-images.githubusercontent.com/776467/172134806-68c06ee3-a032-45bc-a9cf-0cd7ca7288d8.png)

I would like to confirm all extension store badges, so developers can add them on their websites.

Chrome Web Store: https://developer.chrome.com/docs/webstore/branding/
Firefox Add-ons Store: https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/
Safari (I guess using app store brand): https://developer.apple.com/app-store/marketing/guidelines/
Edge: ?

Developers requirements:
- Format: svg or other vector format is the best, png is the second.
- Size: at least, developers need to adjust them to the same height.

Current states:

- Chrome: 2 styles(border or no border), 3-sizes, png and ai files.
- Firefox: 1 style, 2-sizes, only png files.
- Safari(App Store): 2 styles x Black/White x 41 languages, esp and svg files.

**Comment by anjocerdena** [comment]
Opera also has a page documenting their add-ons badge here: [https://dev.opera.com/extensions/branding-guidelines/](https://dev.opera.com/extensions/branding-guidelines/)

**Comment by carlosjeurissen** [comment]
A bit off-topic for this community, however seems some alignment in terms of install-badge would be very welcome for developers.

In addition, it seems these badges could receive an update. For example, the Chrome Web Store icon is outdated in this badge after the new Google Chrome icon.

**Comment by hanguokai** [comment]
Yes, this is not a technical issue. My intention is to make it easy for developers to find these design resources in one place, and remind browser vendors to supply/update/improve them.

I close it now. But welcome to keep commenting by developers and browser vendors.

**Comment by hanguokai** [comment]
Here is Microsoft Store Badge: https://docs.microsoft.com/en-us/windows/uwp/publish/app-marketing-guidelines

For example
![English_get it from MS_864X312](https://user-images.githubusercontent.com/776467/186943317-bc76e327-caaf-4905-98e6-0ae248f367db.png)
![English_get](https://user-images.githubusercontent.com/776467/186943348-91a2d70c-d74e-4a36-8eda-ec59f7a07fd6.png)
