### ISSUE TITLE
WECG at TPAC 2022

### ISSUE THREAD

**Issue by dotproto** [hober/web-extensions#232]
This is a meta issue to track the WebExtension Community Group's involvement with [TPAC 2022](https://www.w3.org/wiki/TPAC/2022).

**Comment by dotproto** [comment]
### Overview

[TPAC][about] (also known as "Annual W3C Conference") is an annual,  unconference-style event hosted by the W3C. TPAC 2022 will be a [hybrid event][blog] (both in-person and virtual). Participants must follow the W3C's [Code of Ethics and Professional Conduct][code].

[Registration fees][reg] are required in order to help offset the cost of the event, but the W3C [provides][waiver] [resources][inclusion] to minimize the effect of cost as a barrier to participate. [Registration will open][reg] at the end of June.

The registration page also advises "people to confirm their meeting registration and payment before making flight arrangements." Building on that, I would also recommend reviewing the [Health rules][health] on Canada's requirements and the on-site W3C Rules before making any purchases.

### Key info

| Title            | Details | 
| ---              | --- |
| Dates            | Monday, September 12 – Friday, September 16 |
| Venues           | - [Sheraton Vancouver Wall Centre][hotel] in Vancouver, Canada<br>- Hub in China (location TBD) |
| Links            | - [Registration][reg]<br>- [Health rules][health]<br>- [Schedule][schedule]<br>- [Venue, accommodations, and transport][venue] |

### Tentative schedule

_This information was copied from the [TPAC Schedule][schedule] on 2022-06-23. Please visit that page for the latest information._

| Day       | Events |
| ---       | --- |
| Monday    | **08:00–18:00**<br>Group meetings;<br>Ethical workshop<br><br>**18:00–19:00**<br>Welcome reception |
| Tuesday   | **07:00–18:00**<br>Group meetings<br><br>**From 18:00**<br>Developer meetup |
| Wednesday | **08:00–18:00**<br>Group meetings;<br>W3C community meetings;<br>Breakout sessions;<br>plenary<br><br>**18:30–21:00**<br>Technical-plenary reception |
| Thursday  | **08:00–18:00**<br>Group meetings;<br>Ethical workshop |
| Friday    | **08:00–18:00**<br>Group meetings |

See the [Participation policies and recommendations][participation] page for guidance on requirements to attend the different types of meetings.

### W3C recommendations

> The goal of Group meetings during a W3C TPAC is to gather the community together, to create momentum and collective brainstorming around challenges faced by the Web. … The benefit of assembling the community for thought-provoking discussions is invaluable.
>
> &mdash; [On TPAC Group and Joint-Group Meetings][meetings]

The page offers a number of suggestions for how groups should approach engaging with TPAC. To reframe the guidance in that article a little, there are three main ways that the article recommends engaging with TPAC:

1. Review the state of our group.
2. Schedule Joint Meetings to advance common interests.
3. Use Breakouts for topics of general interest.

The TPAC 2022 [wiki page][wiki] page also suggests:

1. Recording a 2-3 minute demo or group update video.
2. Joining the developer meetup on Tuesday, September 13.

[about]:         https://www.w3.org/2022/09/TPAC/about.html 
[blog]:          https://www.w3.org/blog/news/archives/9503
[code]:          https://www.w3.org/Consortium/cepc/
[demos]:         https://www.w3.org/wiki/TPAC/2022/Demos_and_Group_updates
[health]:        https://www.w3.org/2022/09/TPAC/health.html
[hotel]:         https://www.marriott.com/en-us/hotels/yvrws-sheraton-vancouver-wall-centre/overview/
[inclusion]:     https://www.w3.org/2022/09/TPAC/registration.html#inclusion-fund
[meetings]:      https://www.w3.org/Guide/meetings/tpac.html
[participation]: https://www.w3.org/2022/09/TPAC/participation.html
[reg]:           https://www.w3.org/2022/09/TPAC/registration.html#fees 
[schedule]:      https://www.w3.org/2022/09/TPAC/Overview.html#schedule
[venue]:         https://www.w3.org/2022/09/TPAC/venue.html
[waiver]:        https://www.w3.org/2022/09/TPAC/registration.html#waiver 
[wiki]:          https://www.w3.org/wiki/TPAC/2022

**Comment by Rob--W** [comment]
We have an assigned meeting slot on the schedule of TPAC 2022, 
on Thursday, September 15th, 13:30 - 15:30 (local time in Vancouver, CA).
Calendar item: https://www.w3.org/events/meetings/7bbba4a3-8305-45cd-a998-67ede8b0a1a1

Note that earlier on that day (8:00 - 9:00 local time in Vancouver), we [already have a regularly scheduled WECG meeting ](https://www.w3.org/groups/cg/webextensions/calendar#card-d7bbce8f-549f-46ea-b440-ea6902f8707c-20220915T080000)(the biweekly one).

Our meeting time at TPAC overlaps with the [Browser Testing and Tools Working Group](https://www.w3.org/events/meetings/d7ec73b1-f9b3-4748-a508-eec1f9751d9a) meeting, but they have [another one on Friday](https://www.w3.org/events/meetings/22258866-0f4b-4711-bede-abdb547500e7). It may be worth trying to make progress on https://github.com/w3c/webextensions/issues/19, since both of our groups are present in person.

Any other topic suggestions?

**Comment by dotproto** [comment]
During today's session I asked the group to share thoughts on groups we should try to work with or specific topics we want to cover in our session. 

**Timothy**
* Service workers WG
* Web app manifest (Web Applications WG) - there's a lot of overlap between the web app manifest and extension manifest

**Carlos**
* CSS WG - how browsers should approach sizing websites that set their own size (popup windows, 

**Rob**
* Browser Tools and Testing WG ([comment](https://github.com/w3c/webextensions/issues/232#issuecomment-1196975450))
* User script managers
* DNR/Web Request

**Simeon** 
* Achieving stated goals in the charter (specifying a common platform)

**Comment by Rob--W** [comment]
Maybe WebAuthn? #238

The [Web Authentication CG](https://www.w3.org/Webauthn/) is also at TPAC - https://www.w3.org/events/meetings/9bb8b8cb-26ac-4258-b409-110809e505b4

May be useful to sync up with them to see how extensions can/should fit in here.

**Comment by timcappalli** [comment]
@Rob--W , @dotproto 
I will be at TPAC and definitely would love to talk about #238

**Comment by timcappalli** [comment]
I will be at TPAC and definitely would love to talk about #238

**Comment by dotproto** [comment]
Today I'm working on the agenda. I've created a doc to gather notes. At the time of posting this message 


I just created a doc to

**Comment by dotproto** [comment]
Today I'm working on the agenda in [this doc](https://docs.google.com/document/d/16WSD8IPhab4lkNTNQb227-OeN9vJ341NLQpI13stmdY/edit#heading=h.ikp1sy9ye3ae). At the time of posting this message, anyone can add comments or suggestions to the doc. I'm planning to make this view only after TPAC.

**Comment by Rob--W** [comment]
TPAC 2022 has completed; the agenda referenced above was copied to the meeting notes at https://github.com/w3c/webextensions/blob/main/_minutes/2022-09-15-wecg-tpac.md

(not to be confused with the meeting a few hours before, at https://github.com/w3c/webextensions/blob/main/_minutes/2022-09-15-wecg.md )

I and @timcappalli haven't managed to chat about WebAuthn, but we can try to cover that async.
