### ISSUE TITLE
[housekeeping] Reorganise github labels

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#233]
The labels can use some cleanup and structure. Currently we have:
agenda, bug, Chrome: follow-up, discussion, documentation, duplicate, enhancement, future topics, good first issue, help wanted, inconsistency, invalid, question, spec clarification, task, topic: automated testing, topic: csp, topic: remote code, topic: secureStorage, topic: service worker, wontfix

My proposal is to start with removing the following unused labels:
bug
duplicate
"help wanted"
wontfix

And start prefixing similar labels to increase structure. Starting with
api: someApiName labels
These labels are used for specific APIs, like `secureStorage`, `action`.

Then we have the `status` labels. Which can include:
`status: needs-discussion`, `status: consensus-reached`,  `status: widely-implemented` and `status: needs-mv-upgrade`
Related issue: https://github.com/w3c/webextensions/issues/205

This issue is created to start the discussion on how we can better organise the community labels.

**Comment by Rob--W** [comment]
I've removed "bug" and "help wanted" since they're clearly not useful for this repo.

"duplicate" and "wontfix" are potentially meaningful, but since there are no existing issues with the label, and the there is no real value in tracking these statuses separately, I've just removed it.

**Comment by xeenon** [comment]
Lets use #244 for this going forward.
