### ISSUE TITLE
Support high DPI image assets on the extension store

### ISSUE THREAD

**Issue by hanguokai** [hober/web-extensions#240]
I'm not sure if the question (non-policy issue) about the extension store can be discussed here, but there's no doubt that developers care. For example, the image assets in the store listing page. **Here I focus on supporting high-resolution images on the extension store, i.e. the size of the icon(logo), screenshots and promotional images(tiles), or support svg files.**

Ref links:
- [A related discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/obZ9t7b8hPk/m/uRm6_aqTAwAJ).
- [Chrome Web Store Supplying Images](https://developer.chrome.com/docs/webstore/images/)
- [Edge Store listing details](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#step-5-add-store-listing-details-for-your-extension)
- [Firefox add-on listing details](https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/)

### Icon (Store logo, Manifest icons)
- Edge: 300x300
- Chrome: 128x128
- Firefox: 32x32 and 64x64, also support svg.

### Screenshots
- CWS currently only accepts 1280x800 or 640x400 images for screenshots. This is a **bad** user experience on a hi-dpi screens.
- Edge store is the same with CWS, but it shows screenshots more clearly, and user can click to view the big picture.
- Firefox is also 1280x800. For other image sizes, we recommend using the 1.6:1 ratio.

In 2022, the extension store should support image assets for hi-dpi screen. For example, if screenshots's aspect ratio is 1.6, it should accept 640x400, 1280x800, 1920x1200, 2560x1600 screenshots.

### Promotional images
Small tile: 440x280 pixels. I usually only provide this size of the promotional image.

**Comment by xeenon** [comment]
As mentioned in the last meeting, extension store issues are out-of-scope in this group.

**Comment by hanguokai** [comment]
I create a [PR](https://github.com/w3c/webextensions/pull/247) to add "Extension stores are out-of-scope" in [Charter](https://github.com/w3c/webextensions/blob/main/charter.md#out-of-scope). So community members can know that in the future.
