### ISSUE TITLE
Upgrading to manifest v3 - 'scripting' permission

### ISSUE THREAD

**Issue by sergey-shpak** [hober/web-extensions#243]
Hey, I'm trying to upgrade extension to the latest manifest v3 version

Since v3 introduces 'scripting' API which has to be used instead of 'tabs.executeScript', as result it forces permissions list update with additional 'scripting' key - will browser disable extension for user permission confirmation in that case?

**Comment by xeenon** [comment]
This question is out of scope for this group, and up the the implementation of each browser.
