### ISSUE TITLE
Main world equivalent of scripting.registerContentScripts

### ISSUE THREAD

**Issue by Jack-Works** [hober/web-extensions#248]
|                | Declarative                      | Imperative              |
|----------------|----------------------------------|-------------------------|
| Main world     | MISSING                          | scripting.executeScript |
| Content Script | scripting.registerContentScripts | scripting.executeScript |

Now developers have to use `browser.webNavigation.onCommitted` to execute main world script.

**Comment by hanguokai** [comment]
Do you mean this feature(https://crbug.com/1330986) ?

**Comment by hanguokai** [comment]
scripting.registerContentScripts already supports `world: "MAIN"` since Chrome 102.

**Comment by Jack-Works** [comment]
Oh! I don't know that, and that feature also does not show on Chrome API page/MDN
