### ISSUE TITLE
Inconsistency: `oldValue` in `storage.StorageChange`

### ISSUE THREAD

**Issue by regseb** [hober/web-extensions#262]
Hi,

I noticed a difference between Firefox and Chromium on the `storage.onChanged` event.

- In Firefox, [`storage.StorageChange`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageChange) always has an `oldValue` property (with `undefined` when there was not old value).
- In Chromium, `storage.StorageChange` has not an `oldValue` property when there was not old value.

## Testcase

- _manifest.json_:

```JSON
{
    "manifest_version": 2,
    "name": "Test case",
    "version": "1.0.0",
    "background": {
        "scripts": ["background.js"]
    },
    "permissions": ["storage"]
}
```

- _background.js_:

```JavaScript
chrome.storage.onChanged.addListener((changes) => {
    console.log(changes.foo);
});
chrome.storage.local.clear(() => {
    chrome.storage.local.set({ foo: "bar" });
    chrome.storage.local.set({ foo: "baz" });
});
```

### Firefox

> { oldValue: undefined, newValue: "bar" }
> { oldValue: "bar", newValue: "baz" }

### Chromium

> { newValue: "bar" }
> { newValue: "baz", oldValue: "bar" }

**Comment by xeenon** [comment]
Safari matches Chrome here.

**Comment by xeenon** [comment]
We resolved in the meeting to close this as it fundamentally does not matter much, fetching `change.oldValue` will result in `undefined` either way. The only impact is key iteration and we decided that was not important enough to warrant a change in browsers here.

**Comment by carlosjeurissen** [comment]
@regseb if this actually causes practical issues when you want to distinguish a new installation from a storage key set to an empty value you can consider using `null` instead of `undefined`. `null` is handled in all browsers when setting storage.
