### ISSUE TITLE
Proposal: declarative way for opening an extension page in a new tab when click the extension icon

### ISSUE THREAD

**Issue by hanguokai** [hober/web-extensions#267]
Popup is a temporary small window. Sometimes, developers want another behavior: open a page in a new tab when users click the extension icon.

At present, developers must declare a background script(service worker), and add one line of code in it:
`browser.action.onClicked.addListener(_ => chrome.tabs.create({url: "index.html"}));`

My proposal likes below:
```
  // manifest.json
  "action": {
    "default_tab_page": "index.html",
  }
```
```
  // action api
  browser.action.getTabPage();
  browser.action.setTabPage('index.html');
```
Unlike popup page, tab page has no per-tab state. When click the extension icon, just open that page in a new tab.

**Comment by fregante** [comment]
This is already trivial to implement, but it's also a very simple request. I would not mind such interface.

**Comment by Rob--W** [comment]
Discussed during the meeting; Since the feature can already trivially be implemented with a background worker/script, it is not necessary to add the functionality to the extension API. Extension API additions are better reserved for features that are difficult to achieve otherwise.

**Comment by carlosjeurissen** [comment]
In the current form, it indeed seems quite trivial to implement something like this.

However, when exploring further options / features, this could start becoming useful. Think about the browser being smart enough to focus the `full tab page` if it is already opened, instead of opening a new one. And/or have this `full tab page` be a pinned tab right away when opening it.

**Comment by Rob--W** [comment]
> In the current form, it indeed seems quite trivial to implement something like this.
> 
> However, when exploring further options / features, this could start becoming useful. Think about the browser being smart enough to focus the `full tab page` if it is already opened, instead of opening a new one. And/or have this `full tab page` be a pinned tab right away when opening it.

If that is the desired result, then we could repurpose the existing default_popup and setPopup APIs along with a new property `open_in_tab` (similar to `options_ui`). Clicking the popup and responding to a click are mutually exclusive anyway.

But unlike options pages and (browser) action panels, opening a new tab is already easily possible with existing extension APIs, which was the reason for closing this feature request.

The participants in the meeting, including representatives of Apple (Timothy), Google (Simeon) and Mozilla (me), were all not against the functionality itself, but after weighing implementation/maintenance effort and balancing that against the benefits to developers, we decided to not add a new API requested here.
