### ISSUE TITLE
Add support for modules in limited event pages

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#289]
Currently Google Chrome supports `"type": "module"` for background serviceWorkers. During our 2022-10-13 meeting, while discussing https://github.com/w3c/webextensions/issues/282, Safari and Firefox agreed it makes sense to also add support `"type": "module"` for [limited event pages](https://github.com/w3c/webextensions/issues/134).

Basically given this syntax in `manifest.json`:
```json
"background": {
  "scripts": ["script1.js", "script2.js"],
  "type": "module"
}
```

The browser would generate a `_generated_background_page.html` which looks like this:
```html
<head></head><body>
<script type="module" src="script1.js"></script>
<script type="module" src="script2.js"></script>
</body>
```

Dedicated issue on the Mozilla bugtracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1811443

**Comment by xeenon** [comment]
I filed this for Safari/WebKit: https://bugs.webkit.org/show_bug.cgi?id=246475

**Comment by Rob--W** [comment]
I filed a new Firefox bug specifically for event pages: https://bugzilla.mozilla.org/show_bug.cgi?id=1811443, since the originally linked Bugzilla issue was about `type="module"` of Service workers.

**Comment by xeenon** [comment]
Safari Technology Preview supports this now, and the Safari 16.4 beta.

**Comment by carlosjeurissen** [comment]
Since this is or will be supported in both Firefox and Safari. And considering Chrome will not support the limited event pages. No further action seems to be needed here.
@Rob--W Seems this has since been implemented Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1811443), can you update the Firefox stand to implemented and subsequently close the issue?
