### ISSUE TITLE
Performance Tracking for Extension Service Workers

### ISSUE THREAD

**Issue by lukeselker** [hober/web-extensions#299]
Hi!

Does anyone know when support for performance tracking for extension service workers will be available?

Thanks!

<img width="598" alt="image (1)" src="https://user-images.githubusercontent.com/32623560/196251321-31343408-3d57-4902-972c-8cc0eb63eab0.png">

**Comment by frivain** [comment]
@dotproto would you have any insight? Maybe we can cover async before the next public meeting?

**Comment by tophf** [comment]
Devtools lacks this feature, but here's a workaround:

1. open any extension page or script or anything like chrome-extension://###/manifest.json
2. open devtools there, go to timeline, start recording (Ctrl-E, the first button)
3. duplicate this tab, open devtools, go to Application -> Service worker -> click stop, click start
4. stop recording in the first tab
5. in the flamechart expand the worker

**Comment by xeenon** [comment]
No action can be taken in this group for this issue. This is a browser specific issue that would be best filed with the Chromium, Firefox, and WebKit bug trackers.

**Comment by carlosjeurissen** [comment]
@lukeselker @frivain @tophf is there already a crbug.com bug for this one?

**Comment by tophf** [comment]
https://crbug.com/1229555
