### ISSUE TITLE
`_execute_action`, `_execute_browser_action` and `_execute_page_action` commands

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#301]
As reported by @beaufortfrancois in https://crbug.com/1371857, there are some issues related to the command to open webExtensions `action`.

### Background
In MV2, this classically was defined as `_execute_browser_action` and `_execute_page_action` for `browserAction` and `pageAction` respectively. In MV3, both were renamed to `_execute_action`.

In the current situation, when a user set a certain shortcut in MV2 for `_execute_browser_action`, then upgrades to MV3 and renames it to `_execute_action`, the shortcut is lost.

### Solution
Internally, browsers should threat `_execute_browser_action`, `_execute_page_action` and `_execute_action` all as equivalent and only store one custom shortcut from the user for all of them. If multiple are found, either stored by the browser, or multiple definitions in the `manifest.json` `commands` key, the `_execute_action` would be preferred.

To assist in the process, browsers should warn about the presence of `_execute_*` if the equivalent `action` key is not present, which would fix: https://crbug.com/1353210

Tracking issue for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1797811

**Comment by beaufortfrancois** [comment]
Thank you @carlosjeurissen ;)

**Comment by carlosjeurissen** [comment]
During our [2022-10-27](https://github.com/w3c/webextensions/pull/305) meeting, Chrome was not supportive of keeping multiple names alive due to the amount of resources this would cost. Support from Firefox is unknown.

As for easing the migration from mv2 to mv3, this is not an issue in Safari, as they do currently not support commands. However, there was consensus between browsers this migration should be handled during the transition from mv2 to mv3.

This can be tracked for Chrome in https://crbug.com/1353210 
Firefox will consider this when further implementing mv3. @Rob--W should we open a separate issue for this in Mozilla Bugzilla?

**Comment by Rob--W** [comment]
This issue is tracked in Firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1797811

**Comment by Rob--W** [comment]
Chromium has fixed the migration issue in https://bugs.chromium.org/p/chromium/issues/detail?id=1371857 .

**Comment by zombie** [comment]
It looks like we can close this, as I would consider this a bug, and since the only issue left is a bug in Firefox, that has a tracking issue,.

**Comment by Rob--W** [comment]
This has been fixed in Firefox 127.
