### ISSUE TITLE
How to join W3c meeting (even if just spectating)

### ISSUE THREAD

**Issue by brunoais** [hober/web-extensions#323]
This is a followup to:
https://github.com/w3c/webextensions/issues/279#issuecomment-1314920175
> > > > 15 November 2022, 08:00 - 08:55 America/Los Angeles.
> > >
> > > @hanguokai Is it open-doors or closed-doors meeting? If open-doors, how can I participate? If cannot participate, how can I assist?
> >
> > @brunoais I think it is an open meeting like regular meetings. You can register a w3c account(no membership required) and join this [group](https://www.w3.org/community/webextensions/) on w3c website. Then you can see this meeting at https://www.w3.org/groups/cg/webextensions/calendar
> 
> @hanguokai I created the account but I can't join the group because I can't login in wordpress to join the group. I already gave about 1h wait between first try and now. I still cannot login in wordpress but I can login in the website

I'm registered in www.w3.org but I can't login in wordpress to goin the [group](https://www.w3.org/community/webextensions/), so I can see the [calendar](https://www.w3.org/groups/cg/webextensions/calendar). What may I be missing?

Note: I removed the offtopic in the other issue. 
@hanguokai: feel free to delete it too.

**Comment by hanguokai** [comment]
I have deleted my related posts in 279.

Can you login w3c website?

**Comment by Rob--W** [comment]
FWIW I cannot log in to Wordpress either. Looks like a potential bug in the W3 site? In any case, a Wordpress account is NOT needed.

To join the WECG, use this link: https://www.w3.org/community/webextensions/join
A login modal will pop up, where you have to input the username (email) and password that you chose when you requested a W3C account.

After that, you should be able to view details needed to join the meeting at https://www.w3.org/groups/cg/webextensions/calendar
Specifically, for the user scripts meeting it is https://www.w3.org/events/meetings/ff23204f-3237-4263-92ef-ec0ae850572e

**Comment by brunoais** [comment]
I just tried,  @hanguokai 
The method from @Rob--W worked.
Unfortunately, I can't join the zoom meeting it wants me to login with an account but I don't have a zoom account.
(seems like I miscalculated the time it would start by 1h too)

To be clear:
> To join the WECG, use this link: https://www.w3.org/community/webextensions/join A login modal will pop up, where you have to input the username (email) and password that you chose when you requested a W3C account.

I can go past that one. The problem is zoom. I don't like their ToS. Do I really need to accept their ToS 🤮 ?

**Comment by Rob--W** [comment]
To summarize, to join the meeting, you need to:

1. Join the WECG at https://www.w3.org/community/webextensions/join.
2. View the calendar details at https://www.w3.org/groups/cg/webextensions/calendar
3. Create a Zoom account, and join the Zoom meeting referenced in the calendar invitation.

**Comment by brunoais** [comment]
> 3\. Create a Zoom account, and join the Zoom meeting referenced in the calendar invitation.

In groups advocating for free and openess, I never expected the process would happen in a platform that is so closed off when there are free (freedom) programs for the task ...
