### ISSUE TITLE
Proposal: Ignore unsupported properties in manifest.json

### ISSUE THREAD

**Issue by erosman** [hober/web-extensions#355]
### Purpose
Using the same `manifest.json` for all browsers

### Proposal
Ignore unsupported properties in `manifest.json`

As mentioned in #282, handling of unsupported properties in `mafinset.json` requires a consensus.

Currently browser specific entries often result in failure.

Examples:
- Firefox Specific: `browser_specific_settings`
- Chrome Specific: `minimum_chrome_version`, `key`

**Comment by Rob--W** [comment]
Duplicate of #14.

Side note: both of your examples (browser_specific_settings and minimum_chrome_version) do not result in hard failures.
