### ISSUE TITLE
Inconsistency: Remove chrome_style/browser_style from options_ui, browser_action, action

### ISSUE THREAD

**Issue by erosman** [hober/web-extensions#366]
### Purpose
A **unified** _(all having or all removing)_ approach and implementation would be beneficial.
MV2-MV3 defaults would benefit from unification.

#### "options_ui"
- Firefox MV2-MV3: `browser_style` default `true`
- Chrome MV2: `chrome_style` default ~`true`~ `false`
- Chrome MV3: removed

#### "browser_action" , "action"
- Firefox MV2-MV3: `browser_style` default `true`
- Chrome MV2: ~`chrome_style` default `true`~ n/a
- Chrome MV3: removed

### Notes
[The chrome_style option cannot be used with manifest version 3.](https://chromium.googlesource.com/chromium/src/+/HEAD/extensions/common/manifest_constants.cc)
See also: #108

**Comment by Rob--W** [comment]
- Chrome intentionally dropped support for `chrome_style`: https://bugs.chromium.org/p/chromium/issues/detail?id=973157
- Safari did intentionally not implement it for the lack of use.
- While Firefox still has the property, the stylesheet associated with it is out of date and unmaintained - https://bugzilla.mozilla.org/show_bug.cgi?id=1458678

**Comment by erosman** [comment]
The purpose of the topic is to maintain consistency, by all implementing `browser/chrome_style` or all dropping it.

As all seem to be opposing it, then Firefox might also consider deprecating it and recommend users to include `browser_style: false`.

The issue is the `default` in Firefox which is `true`, therefore omitting `browser_style` in `manifest.json` is not enough.

**Comment by carlosjeurissen** [comment]
Since it seems most browsers do not prioritize maintaining this browser stylesheet concept. It seems this kind of functionality should, if available at all, be disabled by default.

Considering the browser style is disabled by default in Chrome and Safari, changing the default from `browser_style` to `false` for Mozilla Firefox seems preferred for compatibility and clarity. @Rob--W is this a viable path for Firefox? Potentially restricting the default change to mv3?

**Comment by oliverdunk** [comment]
Looping back from the last meeting as promised - as mentioned in the [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=973157) @Rob--W linked, the styles provided by this option were very outdated. The trouble with maintaining this property is ultimately why we decided to remove it - we could update the styles regularly, breaking extensions relying on them, or leave them alone providing more backwards compatibility but having them slowly get out of sync with the rest of Chrome. Neither seemed ideal.

The suggested approach going forward would be to copy the styles in to your extension if you need them: https://source.chromium.org/chromium/chromium/src/+/main:extensions/renderer/resources/extension.css

I think the suggestion @carlosjeurissen made to remove this in Firefox would be the fastest path to alignment.

**Comment by Rob--W** [comment]
We are going to remove it from Firefox. I filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1827910 to track this specific task.

**Comment by Rob--W** [comment]
I updated the title and positions, because the topic has moved from "support same style" to "drop chrome_style/browser_style".

**Comment by Rob--W** [comment]
Consensus achieved, the remaining task is dropping browser_style from Firefox, which is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1827910

**Comment by carlosjeurissen** [comment]
@erosman for the record, seems `options_ui.chrome_style` was false by default, see:
https://web.archive.org/web/20150321054040/https://developer.chrome.com/extensions/optionsV2#chrome_style

As far as I know `chrome_style` has never existed for `browser_action`, `page_action` or `action`.

**Comment by erosman** [comment]
@carlosjeurissen I cant recall where I got that from. :man_shrugging: 
I will amend the original post, just for clarification.
