### ISSUE TITLE
Inconsistency: declarativeNetRequest rules able to block background requests from other extensions

### ISSUE THREAD

**Issue by sammacbeth** [hober/web-extensions#369]
Extensions' `declarativeNetRequest` rules are able to block requests initiated by other extensions. This is a change from MV2, where `chrome.webRequest` had no visibility of these requests.

## Example

An extension defines the following rule, with the intent of blocking requests to example.com on pages loaded in the browser:
```json
{
    "id": 1,
    "priority": 1,
    "action": {
      "type": "block"
    },
    "condition": {
      "requestDomains": ["example.com"],
      "resourceTypes": [
        "csp_report",
        "font",
        "image",
        "main_frame",
        "media",
        "object",
        "other",
        "ping",
        "script",
        "stylesheet",
        "sub_frame",
        "webbundle",
        "websocket",
        "webtransport",
        "xmlhttprequest"
      ]
    }
  }
```

Should another extension how wish to make a request to `example.com` from their background script/service worker, it will be blocked:
```js
fetch('https://example.com/') // blocked
```

## Current browser status

I tested this in Chrome, Firefox and Safari using these [test extensions](https://github.com/w3c/webextensions/files/11039105/mv3-extension-blocking.zip). Steps to reproduce: 
1. Download the attached zip and extract somewhere.
2. Install the extracted "extension-requests" subdirectory as an unpacked extension. 
3. Open the background console for the extension requests demo extension.
4. Switch to the network panel, and see the requests to https://testpages.kzar.co.uk/ being made every second successfully.
5. Install the "extension-request-blocking-mv3" subdirectory as an unpacked extension.

(For Firefox and Safari minor changes are needed for the extensions to load).
Results:
 - Chrome 111: Requests are blocked (Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1421697)
![Screenshot 2023-03-22 at 11 44 06](https://user-images.githubusercontent.com/248111/226879702-e362b26b-3125-4780-b1c0-efcc4c72459a.png)
 - Firefox Developer Edition 112: Requests are blocked
![Screenshot 2023-03-22 at 11 29 31](https://user-images.githubusercontent.com/248111/226880007-6d658700-a544-44ff-921a-c1c20267839a.png)
 - Safari Technology Preview 165: Requests are not blocked

## Discussion

We came across this issue due to a user reported issue on our extension repo (https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732). A `youtube.com` block rule was preventing the FeedBro extension from fetching RSS feeds from their background page. This was unexpected for us, as these requests are not visible in `chrome.webRequest`.

The issue can be mitigated by using a `excludedTabIds: [-1]` condition, however this also prevents the rule from matching requests initiated by website service workers (which is important for tracker blockers).

I believe this issue will introduce significant unexpected extension breakage, plus introduce new ways for extensions to sabotage each other. For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.

**Comment by erosman** [comment]
>  For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.

The opposite is also worth considering.
A privacy extension settings rules but other extensions bypassing those rules, thus relaxing the privacy aspect.

**Comment by Rob--W** [comment]
This topic was already discussed at the previous meeting (PR with meeting notes: #363), with vendor-specific issues tracked at https://crbug.com/1421697 (Chrome) and https://bugzil.la/1810753 (Firefox). The consensus is to not let extensions affect requests from other extensions.

For reference, the notes from two weeks ago are:
https://github.com/w3c/webextensions/blob/6183ce79810c87c3b9fa462f8df7b7345720aa9f/_minutes/2023-03-16-wecg.md?plain=1#L109-L121

The above position was repeated in today's meeting notes (pending review to be merged at #371).

**Comment by erosman** [comment]
There are a number of areas for consideration.

### Rule Contexts

- **All**
  All requests
  e.g. for a privacy extension

- **Self**
  Requests originated from extension itself only
  e.g. adding/modifying own `fetch/XmlHttpRequest` headers

- **Browser**
  Requests not-originated from an extension
  e.g. not interfering with another extension

- **Other** ? (can be merged with browser context)
  Requests originated from other extensions 


For example, `condition.initiatorDomains` may include a keyword to apply context e.g. *all, browser, self, other*.


### Problem Areas

- Privacy extension setting rules but another extension bypassing them
- One extension interfering with another extension's legitimate operation
- Extension interfering with browser's operation

**Comment by Dalzhim** [comment]
@erosman : Rule contexts are important for me and they're also an area where there's a lot of inconsistency right now. Here's what I have observed when trying to use declarativeNetRequest to provide credentials for matching requests.

```
                                     Firefox  Chrome  Safari
Content script fetch                 ✅       ✅      ✅
Content script WebSocket             ✅       ✅      ✅
Background service worker fetch      ✅       ✅      ❌ 
Background service worker WebSocket  ✅       ❌      ❌ 
```

These results are produced with this dynamic rule:

```
function getExtensionDomain()
{
	return new URL(chrome.runtime.getURL("")).hostname;
}

function startModifyingBackgroundRequests(token)
{
	return chrome.declarativeNetRequest.updateDynamicRules({
		removeRuleIds: [12354],
		addRules: [
			{
				"id": 12354,
				"priority": 1,
				"condition": {
					"initiatorDomains": [getExtensionDomain()],
					"requestDomains": ["example.com"],
					"resourceTypes": ["websocket", "xmlhttprequest"]
				},
				"action": {
					"type": "modifyHeaders",
					"requestHeaders": [
						{
							"operation": "set",
							"header":"Cookie",
							"value": ("__Secure-token=" + token)
						},
						{
							"operation": "set",
							"header":"Authorization",
							"value": ("Bearer " + token)
						}
					]
				}
			}
		]
	});
}
```

I would expect to be able to modify headers of my own extension in the background service worker on all browsers, but unfortunately it doesn't seem possible right now, and it's not clear whether these inconsistencies are being tracked.

**Comment by smalluban** [comment]
At Ghostery, we have a similar issue with the problem (mentioned above).

One of our users reported a broken page of another extension, which was blocked by our DNR rules. Everything except the DNR rules does not work (the extension does not receive any events from other extension pages, etc). Also, It is not possible to add a general allow rule to let requests get through. 

As the extensions do not have access to each other, DNR rules should not run for the `chrome-extension://` protocols.

**Comment by kzar** [comment]
For folks following along here, we merged a [fix for this in Chromium](https://chromiumdash.appspot.com/commit/486d638e6977dad73bd207dc914df9319afac152) last night.

**Comment by Lovesbarber100** [comment]
> Extensions' `declarativeNetRequest` rules are able to block requests initiated by other extensions. This is a change from MV2, where `chrome.webRequest` had no visibility of these requests.
> 
> ## Example
> An extension defines the following rule, with the intent of blocking requests to example.com on pages loaded in the browser:
> 
> ```json
> {
>     "id": 1,
>     "priority": 1,
>     "action": {
>       "type": "block"
>     },
>     "condition": {
>       "requestDomains": ["example.com"],
>       "resourceTypes": [
>         "csp_report",
>         "font",
>         "image",
>         "main_frame",
>         "media",
>         "object",
>         "other",
>         "ping",
>         "script",
>         "stylesheet",
>         "sub_frame",
>         "webbundle",
>         "websocket",
>         "webtransport",
>         "xmlhttprequest"
>       ]
>     }
>   }
> ```
> 
> Should another extension how wish to make a request to `example.com` from their background script/service worker, it will be blocked:
> 
> ```js
> fetch('https://example.com/') // blocked
> ```
> 
> ## Current browser status
> I tested this in Chrome, Firefox and Safari using these [test extensions](https://github.com/w3c/webextensions/files/11039105/mv3-extension-blocking.zip). Steps to reproduce:
> 
> 1. Download the attached zip and extract somewhere.
> 2. Install the extracted "extension-requests" subdirectory as an unpacked extension.
> 3. Open the background console for the extension requests demo extension.
> 4. Switch to the network panel, and see the requests to https://testpages.kzar.co.uk/ being made every second successfully.
> 5. Install the "extension-request-blocking-mv3" subdirectory as an unpacked extension.
> 
> (For Firefox and Safari minor changes are needed for the extensions to load). Results:
> 
> * Chrome 111: Requests are blocked (Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1421697)
>   ![Screenshot 2023-03-22 at 11 44 06](https://user-images.githubusercontent.com/248111/226879702-e362b26b-3125-4780-b1c0-efcc4c72459a.png)
> * Firefox Developer Edition 112: Requests are blocked
>   ![Screenshot 2023-03-22 at 11 29 31](https://user-images.githubusercontent.com/248111/226880007-6d658700-a544-44ff-921a-c1c20267839a.png)
> * Safari Technology Preview 165: Requests are not blocked
> 
> ## Discussion
> We came across this issue due to a user reported issue on our extension repo ([duckduckgo/duckduckgo-privacy-extension#1732](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732)). A `youtube.com` block rule was preventing the FeedBro extension from fetching RSS feeds from their background page. This was unexpected for us, as these requests are not visible in `chrome.webRequest`.
> 
> The issue can be mitigated by using a `excludedTabIds: [-1]` condition, however this also prevents the rule from matching requests initiated by website service workers (which is important for tracker blockers).
> 
> I believe this issue will introduce significant unexpected extension breakage, plus introduce new ways for extensions to sabotage each other. For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.

Up

**Comment by Rob--W** [comment]
I have added "implemented: chrome" because the behavior was changed in https://github.com/w3c/webextensions/issues/369#issuecomment-2188561403

I am also changing "supportive: firefox" to "implemented: firefox", since Firefox has restricted extensions from affecting other extensions from the very beginning.

**Comment by redbone755** [comment]
Open

**Comment by manyny2018-droid** [comment]
> Extensions' `declarativeNetRequest` rules are able to block requests initiated by other extensions. This is a change from MV2, where `chrome.webRequest` had no visibility of these requests.
> 
> ## Example
> An extension defines the following rule, with the intent of blocking requests to example.com on pages loaded in the browser:
> 
> {
>     "id": 1,
>     "priority": 1,
>     "action": {
>       "type": "block"
>     },
>     "condition": {
>       "requestDomains": ["example.com"],
>       "resourceTypes": [
>         "csp_report",
>         "font",
>         "image",
>         "main_frame",
>         "media",
>         "object",
>         "other",
>         "ping",
>         "script",
>         "stylesheet",
>         "sub_frame",
>         "webbundle",
>         "websocket",
>         "webtransport",
>         "xmlhttprequest"
>       ]
>     }
>   }
> Should another extension how wish to make a request to `example.com` from their background script/service worker, it will be blocked:
> 
> fetch('https://example.com/') // blocked
> ## Current browser status
> I tested this in Chrome, Firefox and Safari using these [test extensions](https://github.com/w3c/webextensions/files/11039105/mv3-extension-blocking.zip). Steps to reproduce:
> 
> 1. Download the attached zip and extract somewhere.
> 2. Install the extracted "extension-requests" subdirectory as an unpacked extension.
> 3. Open the background console for the extension requests demo extension.
> 4. Switch to the network panel, and see the requests to https://testpages.kzar.co.uk/ being made every second successfully.
> 5. Install the "extension-request-blocking-mv3" subdirectory as an unpacked extension.
> 
> (For Firefox and Safari minor changes are needed for the extensions to load). Results:
> 
> * Chrome 111: Requests are blocked (Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1421697)
>   ![Screenshot 2023-03-22 at 11 44 06](https://user-images.githubusercontent.com/248111/226879702-e362b26b-3125-4780-b1c0-efcc4c72459a.png)
> * Firefox Developer Edition 112: Requests are blocked
>   ![Screenshot 2023-03-22 at 11 29 31](https://user-images.githubusercontent.com/248111/226880007-6d658700-a544-44ff-921a-c1c20267839a.png)
> * Safari Technology Preview 165: Requests are not blocked
> 
> ## Discussion
> We came across this issue due to a user reported issue on our extension repo ([duckduckgo/duckduckgo-privacy-extension#1732](https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732)). A `youtube.com` block rule was preventing the FeedBro extension from fetching RSS feeds from their background page. This was unexpected for us, as these requests are not visible in `chrome.webRequest`.
> 
> The issue can be mitigated by using a `excludedTabIds: [-1]` condition, however this also prevents the rule from matching requests initiated by website service workers (which is important for tracker blockers).
> 
> I believe this issue will introduce significant unexpected extension breakage, plus introduce new ways for extensions to sabotage each other. For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.

**Comment by abdallh12345** [comment]
> Extensions' `declarativeNetRequest` rules are able to block requests initiated by other extensions. This is a change from MV2, where `chrome.webRequest` had no visibility of these requests.
> 
> ## Example
> 
> An extension defines the following rule, with the intent of blocking requests to example.com on pages loaded in the browser:
> ```json
> {
>     "id": 1,
>     "priority": 1,
>     "action": {
>       "type": "block"
>     },
>     "condition": {
>       "requestDomains": ["example.com"],
>       "resourceTypes": [
>         "csp_report",
>         "font",
>         "image",
>         "main_frame",
>         "media",
>         "object",
>         "other",
>         "ping",
>         "script",
>         "stylesheet",
>         "sub_frame",
>         "webbundle",
>         "websocket",
>         "webtransport",
>         "xmlhttprequest"
>       ]
>     }
>   }
> ```
> 
> Should another extension how wish to make a request to `example.com` from their background script/service worker, it will be blocked:
> ```js
> fetch('https://example.com/') // blocked
> ```
> 
> ## Current browser status
> 
> I tested this in Chrome, Firefox and Safari using these [test extensions](https://github.com/w3c/webextensions/files/11039105/mv3-extension-blocking.zip). Steps to reproduce: 
> 1. Download the attached zip and extract somewhere.
> 2. Install the extracted "extension-requests" subdirectory as an unpacked extension. 
> 3. Open the background console for the extension requests demo extension.
> 4. Switch to the network panel, and see the requests to https://testpages.kzar.co.uk/ being made every second successfully.
> 5. Install the "extension-request-blocking-mv3" subdirectory as an unpacked extension.
> 
> (For Firefox and Safari minor changes are needed for the extensions to load).
> Results:
>  - Chrome 111: Requests are blocked (Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1421697)
> ![Screenshot 2023-03-22 at 11 44 06](https://user-images.githubusercontent.com/248111/226879702-e362b26b-3125-4780-b1c0-efcc4c72459a.png)
>  - Firefox Developer Edition 112: Requests are blocked
> ![Screenshot 2023-03-22 at 11 29 31](https://user-images.githubusercontent.com/248111/226880007-6d658700-a544-44ff-921a-c1c20267839a.png)
>  - Safari Technology Preview 165: Requests are not blocked
> 
> ## Discussion
> 
> We came across this issue due to a user reported issue on our extension repo (https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732). A `youtube.com` block rule was preventing the FeedBro extension from fetching RSS feeds from their background page. This was unexpected for us, as these requests are not visible in `chrome.webRequest`.
> 
> The issue can be mitigated by using a `excludedTabIds: [-1]` condition, however this also prevents the rule from matching requests initiated by website service workers (which is important for tracker blockers).
> 
> I believe this issue will introduce significant unexpected extension breakage, plus introduce new ways for extensions to sabotage each other. For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.

Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.comabdallhsaeed600@outlook.comJapan's Nikkei index fell by 5.4%, the biggest drop since the April tariff sell-offhttps://sosovalue.com/research/20308007723044741120x1548757B412A841c83ee3e7dB02A161802e30CFEEmily@enpass.io abdallh@bizreach.co.jp abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.com abdallh100100@gmail.com aaaabdallh500@gmail.com Abdallh5555550@gmail.com Abdallh60036677@gmail.com Abdallhsaeed986@gmail.com abdallh159415@gmail.coml noreply@mailer.solscan.io Microsoft aaaanjuxxyyn2j SwiftKeyhttps://miniapp.yo.xyz/?advertiser_id=abfaf572-5076-4f02-afc0-8492e069c4d8&placement_id=c2082f8b-da2d-456a-a7e5-e4409c19738b&publisher_id=bitget&ref=bitget&sp_cid=0ed810b0-6f74-48e0-9de7-db619848536d&sp_id=5b26003b-f6b7-400e-a6ad-09b29b05c2c4&unit_id=3dfe1773-f215-4997-be44-297bdc5b400chttps://developers.google.com/identity/protocols/oauth2/policies#browsersAbdallh5555550@gmail.com 🆖https://www.gstatic.com/marketing-cms/assets/images/70/13/80b12e8440858a2adbb93163bbca/chrome.png=s96-fcrop64=1,00000000ffffffff-rwhttps://www.terabox.comabdallh60036677@gmail.comhttps://ordiscan.com/rune/MAGICINTERNETMONEYhttps://ordiscan.com/rune/JESUSCHRISThttps://ordiscan.com/rune/TRAGICEDENhttps://ordiscan.com/rune/JESUSCHRISThttps://ordiscan.com/rune/RUNEKOIShttps://ordiscan.com/tx/51274ad4174c99b7d6822993c90bd07cf3e46ea82d18d26a3e09c1591ca716fahttps://ordiscan.com/sat/1021623770965843https://ordiscan.com/sat/1999971875000000https://ordiscan.com/sat/1999972187499999

**Comment by chhlongbeum-hub** [comment]
> Extensions' `declarativeNetRequest` rules are able to block requests initiated by other extensions. This is a change from MV2, where `chrome.webRequest` had no visibility of these requests.
> 
> ## Example
> 
> An extension defines the following rule, with the intent of blocking requests to example.com on pages loaded in the browser:
> ```json
> {
>     "id": 1,
>     "priority": 1,
>     "action": {
>       "type": "block"
>     },
>     "condition": {
>       "requestDomains": ["example.com"],
>       "resourceTypes": [
>         "csp_report",
>         "font",
>         "image",
>         "main_frame",
>         "media",
>         "object",
>         "other",
>         "ping",
>         "script",
>         "stylesheet",
>         "sub_frame",
>         "webbundle",
>         "websocket",
>         "webtransport",
>         "xmlhttprequest"
>       ]
>     }
>   }
> ```
> 
> Should another extension how wish to make a request to `example.com` from their background script/service worker, it will be blocked:
> ```js
> fetch('https://example.com/') // blocked
> ```
> 
> ## Current browser status
> 
> I tested this in Chrome, Firefox and Safari using these [test extensions](https://github.com/w3c/webextensions/files/11039105/mv3-extension-blocking.zip). Steps to reproduce: 
> 1. Download the attached zip and extract somewhere.
> 2. Install the extracted "extension-requests" subdirectory as an unpacked extension. 
> 3. Open the background console for the extension requests demo extension.
> 4. Switch to the network panel, and see the requests to https://testpages.kzar.co.uk/ being made every second successfully.
> 5. Install the "extension-request-blocking-mv3" subdirectory as an unpacked extension.
> 
> (For Firefox and Safari minor changes are needed for the extensions to load).
> Results:
>  - Chrome 111: Requests are blocked (Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1421697)
> ![Screenshot 2023-03-22 at 11 44 06](https://user-images.githubusercontent.com/248111/226879702-e362b26b-3125-4780-b1c0-efcc4c72459a.png)
>  - Firefox Developer Edition 112: Requests are blocked
> ![Screenshot 2023-03-22 at 11 29 31](https://user-images.githubusercontent.com/248111/226880007-6d658700-a544-44ff-921a-c1c20267839a.png)
>  - Safari Technology Preview 165: Requests are not blocked
> 
> ## Discussion
> 
> We came across this issue due to a user reported issue on our extension repo (https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/1732). A `youtube.com` block rule was preventing the FeedBro extension from fetching RSS feeds from their background page. This was unexpected for us, as these requests are not visible in `chrome.webRequest`.
> 
> The issue can be mitigated by using a `excludedTabIds: [-1]` condition, however this also prevents the rule from matching requests initiated by website service workers (which is important for tracker blockers).
> 
> I believe this issue will introduce significant unexpected extension breakage, plus introduce new ways for extensions to sabotage each other. For example, an extension could prevent a privacy extension from fetching updates to their blocklist rules.
__https://www.instagram.com/shoryashah1?igsh=Njg3cDRtNnlkOXZv

**Comment by arturmarciniak010-ctrl** [comment]
Ok lets do it give me the ...
