### ISSUE TITLE
Inconsistency: Return type of `chrome.scripting.executeScript`

### ISSUE THREAD

**Issue by sammacbeth** [hober/web-extensions#373]
In the Chrome documentation, chrome.scripting.executeScript asynchronously returns an array of [InjectionResult](https://developer.chrome.com/docs/extensions/reference/scripting/#type-InjectionResult), which contains the actual return value of the executed script for each frame under the 'result' attribute of the InjectionResult:
```typescript
type InjectionResult = {
  documentId: string;
  frameId: number;
  result: any;
}
```
Firefox and Safari return types differ from Chrome:
 - In Firefox, the `InjectionResult` object [differs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/executeScript#return_value) in that:
   - `documentId` is not included.
   - `error: any` may be included if the script threw or rejected with an error.
 - In Safari, `executeScript` returns `any[]`, which is an array of the script result value, with no additional metadata.

For example, given the following code:
```javascript
const result = await chrome.scripting.executeScript({
  target: {
    tabId: tab.id,
  },
  world: 'ISOLATED',
  func: () => {
    return document.location.href;
  },
});
```
In Chrome the value of `result` might be:
```js
[{ documentId: '...', frameId: 42, result: 'https://example.com/' }]
```
While, in Safari the `result` would be:
```js
['https://example.com/']
```

Steps to reproduce the Safari inconsistency can be seen in this test-case: https://github.com/sammacbeth/mv3-compat-tests/blob/main/Shared%20(Extension)/Resources/tests/test.scripting.js#L6-L27. I've also filed a Safari issue for this (#FB12074764).

**Comment by Rob--W** [comment]
> Firefox and Safari return types differ from Chrome:
> 
>   * In Firefox, the `InjectionResult` object [differs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/executeScript#return_value) in that:
>       
>     * `documentId` is not included.

Firefox has not implemented the `documentId` concept yet. When we do, we will include it.

>    * `error: any` may be included if the script threw or rejected with an error.

Chrome should support the "error" property eventually: https://bugs.chromium.org/p/chromium/issues/detail?id=1271527

>  * In Safari, `executeScript` returns `any[]`, which is an array of the script result value, with no additional metadata.

That looks like a significant issue worth fixing.

**Comment by xeenon** [comment]
We are planning to fix this inconsistency with Safari to return an array of objects with the frameId and result keys.

**Comment by kiaraarose** [comment]
The latest Safari beta should return an array of objects now. Still planning to add support for the error key in the future.
