### ISSUE TITLE
Inconsistency: DNR Redirect Action using regexSubstitution

### ISSUE THREAD

**Issue by lukeselker** [hober/web-extensions#379]
The DNR `redirect` action type allows for 4 optional properties: `extensionPath`, `regexSubstitution`, `transform`,  and `url`. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/Redirect

Sample Rule Configuration:

```
browser.declarativeNetRequest.updateDynamicRules({ addRules: [
  { 
    action: {redirect: {regexSubstitution: "[https://www.somesite.com/\\1](https://www.somesite.com///1)"}, type: "redirect"}, 
    condition: {regexFilter: ".*?://test/(.*?)", resourceTypes: ["main_frame"]}, 
    priority: 1, 
    id: 1,
  }
]})
```

When updating rules, there are no issues when specifying in Firefox/Chrome, but when specifying in Safari, the following error is thrown by the browser: 

```
`redirect` is missing either a `url`, `extensionPath`, or `transform` key
```

It seems that this should be supported, and the issue has been reported here as well - https://bugs.webkit.org/show_bug.cgi?id=244475

**Comment by lukeselker** [comment]
Hi,

It seems that this issue has been resolved as of the latest Safari Technology Preview. However, after getting past this I ran into another inconsistency with redirects. I've opened another issue here (https://github.com/w3c/webextensions/issues/381)

**Comment by zombie** [comment]
Confirmed from the Safari team as resolved in current STP, closing.
