### ISSUE TITLE
Provide a mock way to test upgrade extensions from the extension store

### ISSUE THREAD

**Issue by hanguokai** [hober/web-extensions#382]
This is a feature request for debugging and testing purpose. Because extensions stores have many policy requirements and review process, it is almost impossible for developers to actually test this particular process of upgrading an extension from the extension store.

Some usage scenarios:
- test `runtime.onInstalled` event
- test if an extension will be disabled for permissions change. and test the subsequent process.
- Sometimes developers don't encounter problems in developing mode locally, but occasionally they find problems during the upgrade process. This situation requires trying to reproduce the problem, which requires do upgrade many times, but only for debugging purposes.

Note: current "reload" and "enable/disable" buttons cannot 100% simulate the code path of the upgrade process from the extension store.

**Comment by hanguokai** [comment]
For Chrome, I find a easy way to simulate the upgrade process locally in unpacked mode: **drag the same folder to chrome://extensions** . It's similar to clicking the reload button, but it even works when the extension is disabled. I'm not sure this method is exactly the same as upgrading from the extension store, e.g. it doesn't trigger new warning permission behavior (disable the extension and prompt granting new permission).

**Comment by dotproto** [comment]
To build on [this comment](https://github.com/w3c/webextensions/issues/382#issuecomment-1517147834), developers don't have a single way to test the upgrade flow for an extension. Instead, they must use two very similar flows to test different aspects of the installation:

1. Upgrading an unpacked extension to test extension functionality
2. Upgrading a self-signed extension to test permission upgrades

At the moment, it's only possible to test the upgraded process in a single flow by doing the self-signed upgrade test on Linux.

IMO it should be possible to test the upgrade flow using an automated process. This includes checking if the extension is disabled for permission upgrades and, if so, retrieving the text and/or a screenshot of the the prompt presented to the end user.

**Comment by Rob--W** [comment]
FYI there are browser-specific mechanisms to test updates:

- Firefox: https://extensionworkshop.com/documentation/manage/updating-your-extension/
- Chrome: https://developer.chrome.com/docs/extensions/mv3/hosting/ , specifically https://developer.chrome.com/docs/extensions/mv3/linux_hosting/

**Comment by dotproto** [comment]
@xeenon, could you follow up with info on how to test upgrades in Safari?

**Comment by xeenon** [comment]
Safari 16.4 has a similar alert that disables the extension on permission expansion. This flow also happens when building and running from Xcode during development.

**Comment by patrickkettner** [comment]
While this is an important concept in testing, it is fully dependent on browser UI and stores, so the WECG determined it is out of scope for the WECG. 

Chrome has the [extension-update-testing-tool](https://github.com/GoogleChromeLabs/extension-update-testing-tool), 
Firefox has [their docs](https://extensionworkshop.com/documentation/manage/updating-your-extension#testing-automatic-updating), and Safari is investigating making this easier.
