### ISSUE TITLE
WECG at TPAC 2023

### ISSUE THREAD

**Issue by dotproto** [hober/web-extensions#385]
The W3C will be holding [TPAC 2023](https://www.w3.org/2023/09/TPAC/Overview.html) in Seville, Spain on September 11-15. This thread will serve as our primary discussion area for planning and scheduling purposes. 

Chairs and editors, please the summary information here as up to date as reasonably possible.

#### Meeting times

* Monday 11 September: 17:00 - 18:30 CEST (8:00 - 9:30 AM PDT)
* Tuesday 12 September: 17:00 - 18:30 CEST (8:00 - 9:30 AM PDT)

#### Topics

For the agenda, see https://github.com/w3c/webextensions/issues/385#issuecomment-1710769877

### Attendees

* @carlosjeurissen (Jeurissen Apps)
* @dotproto (unaffiliated)
* @oliverdunk (Google)
* @irew (Dashlane)
* @kiaraarose (Apple)
* @patrickkettner (Google)
* @rdcronin (Google)
* @rdworth (Capital One)
* @Rob--W (Mozilla)
* @sammacbeth (DuckDuckGo)
* @zombie  (Mozilla)

**Comment by dotproto** [comment]
**Scheduling notes**

I've tentatively signed us up for 3x 90 minute sessions over the course of four days. The available time slots were 09:30 - 11:00, 11:30 - 13:00, 14:30 - 16:30, and 17:00 - 18:30. I selected the latest time slot available because it matches our current public meeting times and maximizes the likelihood that participants on the US West Coast will be able to attend.

I expect this will be a popular time slot. If they cannot accommodate all groups aiming for that time slot, we may be asked to meet during the 14:30 - 16:30 window. I will follow up with any news on this front.

**Comment by dotproto** [comment]
During our 2023-05-25 meeting I mentioned that I had some thoughts on how we could use our sessions if we don't have explicit topics we want to discuss ahead of time. 

First, since all of our sessions start at 8:00 AM Pacific time, I'd suggest that we use the first 45 minutes of our Thursday session as a typical WECG public meeting and the second half would be a retrospective of the group's work over the past year.

At the moment we don't have a specific set of topics that we would like to discuss in our Monday and Tuesday sessions. Based on last year, I think there's a strong chance we may have have firm plans by the time the event arrives. As such, I propose that we use an unconference-style approach for these sessions. Here's roughly what I have in mind:

* 10 min: Participants propose topics for discussion.
* 5 min: Participants vote on topics.
* 20 min: Discuss the # 1 voted topic
* 10 min break
* 20 min: Discuss the # 2 voted topic
* 20 min: Discuss the # 3 voted topic

That leaves 5 minutes that will likely be consumed as we transition between topics.

**Comment by oliverdunk** [comment]
I'll be attending TPAC in person.

**Comment by patrickkettner** [comment]
I'll be attending TPAC in person.

**Comment by rdworth** [comment]
I'll be attending TPAC in person

**Comment by zombie** [comment]
From Mozilla, Rob and me plan to attend in person.

We have interest from the l10n/i18n community to talk with them about the upcoming Message Format 2, and how it might interact with extensions ([ref1](https://github.com/unicode-org/message-format-wg), [ref2](https://github.com/tc39/proposal-intl-messageformat)).

**Comment by dotproto** [comment]
The Monday and Tuesday sessions were approved, but we didn't get the Thursday session.

**Comment by sammacbeth** [comment]
I'll be attending in person from DuckDuckGo.

**Comment by carlosjeurissen** [comment]
I'll be attending in person.

**Comment by kiaraarose** [comment]
From Apple, I'll be attending in person.

**Comment by rdcronin** [comment]
I'll be attending in-person from Chrome.

**Comment by dotproto** [comment]
Here's an updated schedule for next week. This covers both of our official TPAC sessions and our regularly scheduled meeting on Thursday.

**Monday, 17:00 - 18:30 CEST**

| Time (CEST) | Duration | Topic |
| --- | --- | --- |
| 17:00 | 5 min | Intro |
| 17:05 | 20 min | WECG meeting structure and follow-up |
| 17:25 | 20 min | Automated compatibility testing |
| 17:45 | 10 min | Break |
| 17:55 | 20 min | Web API integration |
| 18:15 | 15 min | Open discussion |
| 18:30 | --- | End |

**Tuesday, 17:00 - 18:30 CEST**

| Time (CEST) | Duration | Topic |
| --- | --- | --- |
| 17:00 | 5 min | Intro |
| 17:05 | 20 min | Automated compatibility testing |
| 17:25 | 25 min | Declarative Net Request |
| 17:50 | 20 min | User Script API |
| 18:10 | 20 min | WebAuthn RP ID |
| 18:30 | --- | End |

**Thursday, 17:00 - 18:00 CEST**

| Time (CEST) | Duration | Topic |
| --- | --- | --- |
| 17:00 | 30 min | Follow-up from TPAC conversations |
| 17:30 | 30 min | Abbreviated WECG session |
| 18:00 | --- | End |

**Comment by irew** [comment]
👋🏽 From Dashlane, I'll be attending in person.

If possible I'd like to discuss this issue https://github.com/w3c/webextensions/issues/238.

**Comment by dotproto** [comment]
@irew, are you on Matrix? If not, you might want to join in order to help coordinate a discussion in person

**Comment by dotproto** [comment]
TPAC 2023 docs
- [TPAC 2023 - Spec breakout](https://docs.google.com/document/d/1q9hQgwTVvyujEhvr52ALeTtuYxyzFhQPfRwPg_hBXlI/edit#heading=h.hadc52coizf3)
- [TPAC 2023 - WebExtensions informal meeting minutes](https://docs.google.com/document/d/1ebrHySL0oag2u3gnXogM8LuahT397kKDNVRFYQDWy-8/edit#heading=h.d2q8zwxo01k9)
  - Access is currently restricted. We plan to clean up the doc and publish our meeting notes after the event.

**Comment by Rob--W** [comment]
The minutes of the WECG meetings at TPAC 2023 have been published here:

- https://github.com/w3c/webextensions/pull/447
- https://github.com/w3c/webextensions/pull/448
- https://github.com/w3c/webextensions/pull/453
- https://github.com/w3c/webextensions/pull/459
- Spec breakout - https://docs.google.com/document/d/1q9hQgwTVvyujEhvr52ALeTtuYxyzFhQPfRwPg_hBXlI/edit

With the publication of these notes, this issue can now be closed. See you all next year at TPAC 2024!
