### ISSUE TITLE
Proposal: Allow notifications API in content scripts

### ISSUE THREAD

**Issue by erosman** [hober/web-extensions#404]
## Preamble

Content scripts often need to show a notification. At the moment, the process involves adding a listener in the background script and then sending a message to the background script to generate the [notifications.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create).

Notification API should be a safe enough API to be allowed in the [Content Script WebExtension APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis).

## Proposal

Allow [notifications](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications) in the [Content Script WebExtension APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis)

## Purpose

Reduce reliance on the background script/service-worker/event-page
See also: #378, #403

**Comment by zombie** [comment]
After a short discussion in the meeting, we decided against this proposal.  Overall we believe in keeping the API surface of content scripts to a minimum, except when there's a strong use case that is better solved by exposing a specific API to that environment.

Sending a message to the background and (potentially) waking up the event page/service worker doesn't seem too burdensome, and the API is already asynchronous and "global" (not tied to a particular page where a content script is executing), so keeping the current state seems consistent with the API design and intended use.

Also note the regular [web notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) DOM api is available to content scripts, and provides yet another potential option for extensions.
