### ISSUE TITLE
Exposing WebGPU API to extension ServiceWorker

### ISSUE THREAD

**Issue by MiguelsPizza** [hober/web-extensions#411]
Would be nice to have and I can't think of any reason not to expose WebGPU to a service worker considering Webgl is accessible.

It's only exposed to the Window and DedicatedWorkers at the moment. Reference: https://gpuweb.github.io/gpuweb/#navigator-gpu
[Exposed=(Window, DedicatedWorker), SecureContext]

**Comment by patrickkettner** [comment]
talked to eng for us. Chrome is supportive, but would likely just inherit it if/once it is enabled in web service workers.

**Comment by MiguelsPizza** [comment]
> talked to eng for us. Chrome is supportive, but would likely just inherit it if/once it is enabled in web service workers.

Thanks Patrick. I opened another issue for that [here](https://github.com/gpuweb/gpuweb/issues/4197)

**Comment by Rob--W** [comment]
Consensus is that we'd be supportive of this, but that this is something that should happen on the web platform.

As we don't anticipate further discussion here, I'm closing the issue. If needed it can be re-opened later.
