### ISSUE TITLE
Overview of Persistent States of Various APIs

### ISSUE THREAD

**Issue by hanguokai** [hober/web-extensions#424]
There are many extension APIs that can affect some kind of state, and the persistence of these states is often discussed in various issues in WECG, some with clear definitions and some without. Here is a summary of these states and their persistence.

The purpose of this issue is to make a summary.

Let's make a few simple definitions:
- **A**: session only: memory state, they are cleared when meet below situations
- **B**: across browser sessions persistent: quit and restart the browser, upgrade the browser
- **C**: extension upgrade persistent: including reload the extension
- **D**: extension disable and re-enable persistent

| API  | Chrome |
| ------------- | ------------- |
| action.set* (e.g. setBadgeText)| A |
| [alarms](https://developer.chrome.com/docs/extensions/reference/alarms)  | B + C + D (except [a bug](https://crbug.com/1285798)) for now |
| [contextMenus](https://developer.chrome.com/docs/extensions/reference/contextMenus) | B + D |
| [commands](https://developer.chrome.com/docs/extensions/reference/commands) | B + C + D (can't set by api) |
| [downloads.setUiOptions()](https://developer.chrome.com/docs/extensions/reference/downloads/#method-setUiOptions) | A |
| declarativeNetRequest static rules | B + D |
| [declarativeNetRequest.updateDynamicRules()](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateDynamicRules) | B + C + D |
| [declarativeNetRequest.updateSessionRules()](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#method-updateSessionRules) | A |
| [power.requestKeepAwake()](https://developer.chrome.com/docs/extensions/reference/power/#method-requestKeepAwake) | A |
| storage.session | A |
| storage.local | B + C + D |
| static content scripts | B + D |
| [scripting.registerContentScripts()](https://developer.chrome.com/docs/extensions/reference/scripting/#method-registerContentScripts) | B + D: if persistAcrossSessions is true <br> A: if persistAcrossSessions is false |
| proxy.settings.set() | ? |
| [sidePanel.setPanelBehavior()](https://developer.chrome.com/docs/extensions/reference/sidePanel/#method-setPanelBehavior) | B + C + D |

\* This table may not be exhaustive, nor may it be adequately tested. Additions and corrections are welcome, especially for other browsers!

If you want to keep a state persistent across B, C or D, but the default behavior doesn't meet your needs, you need to maintain the state by yourself with `runtime.onStartup()`, `runtime.onInstalled()` and `runtime.onEnabled()`

**Comment by erosman** [comment]
It is worth noting that some WebExtension APIs access and alter the browser settings. These APIs are simply interfaces to set browser settings and therefore have a more persistent nature than other WebExtension APIs.

I think for better clarity, it is worth separating the aforementioned from the others. For example:

- [privacy](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/privacy)
- [proxy.settings](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings)

**Comment by bershanskiy** [comment]
This is a good table to have. This table is missing a few APIs like [`permissions`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions)

**Comment by xeenon** [comment]
While `storage.session` data is not persistent, `storage.session.setAccessLevel()` is persistent in Chrome.

**Comment by hanguokai** [comment]
We discuss this issue at today's meeting. Next step, I'll submit a document (PR) and hand it over to the community for maintenance.

At present, this kind of problem depends on browsers' implementation. The purpose of this document is to provide a high-level perspective on all such issues. The goal is to expect similar issues to be designed and implemented in a consistent manner on the platform, as well as consistent behavior among different browsers.

**Comment by hanguokai** [comment]
Close this issue. Now you can see this doc as a [file](https://github.com/w3c/webextensions/blob/main/memo/persistence-of-states.md) in this repo. Welcome to update it via PR.
