### ISSUE TITLE
Message passing: can't pass file handle or other objects that aren't JSON-serializable

### ISSUE THREAD

**Issue by NV** [hober/web-extensions#430]
Currently, it isn't possible to pass the file handler object using browser.runtime.sendMessage, yet it works fine with window.postMessage.

* browser.runtime.sendMessage requires the message to be [JSON-serializable](https://developer.chrome.com/docs/extensions/mv3/messaging/#:~:text=any%20valid%20JSON%20object).
* postMessage serializes data using the structured clone algorithm, which [allows passing many Web API objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#webapi_types).

I propose to make message-passing object serialization logic work the same as for postMessage.

---

In my particular case, I want an extension to back up data to a file periodically. Currently, I have to use IndexedDB to pass the file handler to the service worker. (There are [more hurdles](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/6vGQ26f9tqQ) to overcome before I could write to a file *periodically*, but those are out of the scope of this proposal.)

**Comment by tophf** [comment]
It's already summarized by Rob--W in https://github.com/w3c/webextensions/issues/293#issuecomment-1310203017.

P.S. For chrome-extension:// scripts (i.e. not content scripts) there's a faster workaround: [serviceWorker messaging](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker/postMessage#examples) (the example calls `register()` but you won't need to).

**Comment by NV** [comment]
Good to know. I'll close it then.

Thanks for the workaround!
