### ISSUE TITLE
Proposal: API to programmatically open the developer tools to a particular panel

### ISSUE THREAD

**Issue by twschiller** [hober/web-extensions#476]
Context
---
- The developer tools can currently only be triggered via keyboard shortcut or the native browser context menu
- That's an onboarding barrier to end-user programming tools that benefit from living in the developer tools (e.g., the application persists across frame navigation)
- Today, low-code/end-user programming tools often choose to instead use floating elements that need to constantly be repositioned/dragged, or use the new sidebar panel API, which is a restrictive form factor
- It also hurts navigational efficiency for developer extensions. There are empty keyboard shortcuts/clicks to open the developer tools and navigate to the particular panel state of interest

Use Cases
---
- Deep linking to a screen in the developer tools panel when the developer tools are not already open. For example:
  - To provide framework-specific "inspect" functionality (e.g., for React Dev Tools)
  - To open an editor for low-code capabilities provided by the extension (e.g., crawler definitions, automation definitions, theme definitions, user scripts, etc.)
- Opening the developer tools as part of an onboarding flow to demonstrate extension usage

Potential API:
---
From the content script:

```
browser.devtools.panels.openPanel({
  // Optional title to match against panels added by `devtools_page`
  title?: string,
  // Optional docking hint, if the user has not previously docked the dev tools
  dockSide?: "left" | "right" | "bottom" | "window"
  // Optional page path to update path for deep linking
  pagePath?: string
})
```

Permissions Considerations
---
- Could require the interaction to come from a user gesture
- Could restrict opening panel to a panel added by the extension
- Currently, enterprise organizations can set a browser policy to restrict access to the developer tools. (Organizations already have control over potential abuse of opening the developer tools.)

Resources/Reference
---
- https://developer.chrome.com/docs/extensions/reference/devtools_panels/

**Comment by Rob--W** [comment]
Every vendor is opposed to an API to open the devtools when it's not already open.

There is more appetite for switching panels when the devtools is already open, but we also need to think of the implications of that.
