### ISSUE TITLE
2024 WECG Face to Face (San Diego)

### ISSUE THREAD

**Issue by zombie** [hober/web-extensions#525]
After a very productive round of WECG meetings at TPAC 2023, which included representatives from most browsers and several community members, we plan to have a similar in-person + online meeting at the Apple office in Rancho Bernardo (outside San Diego), March 18-20 2024:

> 16620 W Bernardo Dr
> San Diego, CA 92127
> United States
>
> https://maps.app.goo.gl/1GLV4gNzNFH5pbew7

We'd like to invite active community members to join us again, as that participation has been valuable at TPAC, so please comment in this issue if you're considering attending.

**Comment by xeenon** [comment]
All of the Safari Extensions team from Apple will be there.

**Comment by patrickkettner** [comment]
I plan on attending

**Comment by oliverdunk** [comment]
I also plan on attending.

**Comment by Rob--W** [comment]
I and @zombie plan on attending on behalf of Mozilla.

**Comment by rdcronin** [comment]
I plan on attending from Chrome.

**Comment by ameshkov** [comment]
I plan on attending.

**Comment by maximtop** [comment]
~I plan on attending too.~
wasn't able to get visa

**Comment by carlosjeurissen** [comment]
I plan on attending.

**Comment by dotproto** [comment]
I'm planning to be there for all 3 days.

**Comment by rdworth** [comment]
I am planning to attend

**Comment by mukul-p** [comment]
I am planning to attend from Microsoft.

**Comment by caseyg1204** [comment]
I am planning to attend Monday and Tuesday

**Comment by xeenon** [comment]
Thanks everyone! We are excited to see you all in San Diego on Monday at 9 am.

**Comment by rdcronin** [comment]
Hello, all!

Apologies for the late notice — we're still ironing out the processes here.

A very rough, very initial, and very subject-to-change agenda of the public sessions is available [here](https://docs.google.com/document/d/1XMPjtBb_nh3_SLcGEeOmdsbaHJwsQ6EgRWZNFoq9vJo/edit) (the doc should be world-viewable).

We'll use our public session tomorrow (from 9a to 10a Pacific Time) for introductions, background, and further elaboration on the continued topics of the meetup.

**Comment by rdcronin** [comment]
Tomorrow morning, we'll be discussing Declarative Net Request (and related) pieces during the public session (scheduled for 9am PT).  This includes cosmetic filtering proposal and other areas of expansion and improvements, safe imperative modification, header modifications, CSP, and more.

**Comment by Rob--W** [comment]
The meeting notes have been published in https://github.com/w3c/webextensions/pull/599 (see the PR for an overview and all discussed issues). Here are the detailed meeting notes themselves:
   * [2024-03-18-san-diego-meetup.md](https://github.com/w3c/webextensions/blob/main/_minutes/2024-03-18-san-diego-meetup.md)
   * [2024-03-19-san-diego-meetup.md](https://github.com/w3c/webextensions/blob/main/_minutes/2024-03-19-san-diego-meetup.md)
   * [2024-03-20-san-diego-meetup.md](https://github.com/w3c/webextensions/blob/main/_minutes/2024-03-20-san-diego-meetup.md)

And with that, there are no more topics to discuss here, so I'll close this issue. Thanks everyone for participating, and see you at the next one! (maybe [TPAC 2024](https://www.w3.org/news-events/w3c-tpac/#upcoming-tpac-2024)?)
