### ISSUE TITLE
Inconsistency: chrome.downloads.open() return value

### ISSUE THREAD

**Issue by bershanskiy** [hober/web-extensions#528]
Update: Firefox and Chromium 123+ now both return `Promise<void>`, Safari does not support this API, but is willing to match.

## Summary

Chromium treats `chrome.downloads.open()` as a sync operation, while Firefox returns `Promise<void>`.

[Chromium bug](https://issues.chromium.org/issues/324567401)

## Details

In Chromium, has the following signature (from [docs](https://developer.chrome.com/docs/extensions/reference/api/downloads#method-open), from [source](https://github.com/chromium/chromium/blob/main/chrome/common/extensions/api/downloads.idl#L524)):
```ts
void chrome.downloads.open(downloadId: number)
```

In Firefox, it returns a Promise (from [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/open)):
```ts
Promise<void> browser.downloads.open(downloadId: number)
```

Safari does not support `downloads` API, but is willing to use promise.

I believe that the function should return `Promise<void>` since opening a file is inherently an async operation. Chromium handles it async ([code](https://github.com/chromium/chromium/blob/main/chrome/browser/extensions/api/downloads/downloads_api.cc#L1547)), but the declaration is sync ([code](https://github.com/chromium/chromium/blob/main/chrome/common/extensions/api/downloads.idl#L524)). It is sync only if there is an error which is known right away like lack of proper permissions or user activation.

(Updated Feb 15, 2024)

**Comment by xeenon** [comment]
Safari does not currently support the downloads API. But I agree a promise makes sense here.

**Comment by bershanskiy** [comment]
@patrickkettner Would you be interested in resolving this difference?

**Comment by patrickkettner** [comment]
Appreciate the ping.
I’ll dig in a bit. I am concerned about it being potentially a breaking
change. I’ll see what the team thinks is plausible

**Comment by patrickkettner** [comment]
Thanks for opening https://chromium-review.googlesource.com/c/chromium/src/+/5274756 ! Checking the existing extension usage, the change seems safe. I pinged a reviewer to get the change merged.

**Comment by bershanskiy** [comment]
The relevant change was merged ([commit](https://github.com/chromium/chromium/commit/c8ae046021c9290aa037ee535241838aee702ece)), Chromium 123+ will return `Promise<void>`.

**Comment by bershanskiy** [comment]
Since the inconsistency is resolved, I'm closing this issue.

We might want to change labels: remove "supportive: chrome" and add "implemented: chrome", "implemented: firefox", "implemented: edge".
