### ISSUE TITLE
Add header to RequestDetails

### ISSUE THREAD

**Issue by Yuki2718** [hober/web-extensions#622]
It seems current DNR doesn't allow to block a request based on details of response header. I'm not talking about modifying header. We uBlock Origin team is now expanding use of [$header](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#header) rules which AdGuard also [supports](https://adguard.com/kb/general/ad-filtering/create-own-filters/#header-modifier) to block revolving adservers.

**Comment by tophf** [comment]
Chrome is currently working on it in https://crbug.com/40727004. It might even partially work in Chrome Canary.

**Comment by MasterKia** [comment]
Duplicate of https://github.com/w3c/webextensions/issues/460?

**Comment by Yuki2718** [comment]
> Duplicate of #460?

Yeah, I should have searched. Only filtered by the label DNR (now added to the issue) and checked by my eyes.
