### ISSUE TITLE
Proposal: API to allow incognito access

### ISSUE THREAD

**Issue by erosman** [hober/web-extensions#658]
### Background

Some APIs, like [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings), require incognito permission.

While extensions can enquire [extension.isAllowedIncognitoAccess](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/isAllowedIncognitoAccess), currently, there is no API for the extension to handle the user option within the extension environment. Extensions are forced to ask users to go to the appropriate browser page in order to allow incognito access.

### Proposal

Add an API to enable extensions to requests incognito access from the users (similar to [permissions.request()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request))

For example:
```js
// via permissions.request
let permission = await browser.permissions.request({permissions: ['incognito']});
// return true/false

// via own API
let incognito = await browser.extension.requestIncognitoAccess();
// return true/false
```

See also:
- #429 
- #573

**Comment by Rob--W** [comment]
FYI: starting from Firefox 129, the ability to access private browsing windows is part of the install dialog (https://bugzilla.mozilla.org/show_bug.cgi?id=1842832). Up until Firefox 128, there was a post-install panel from which users can easily grant access to private browsing mode.

After install, it is not obvious for users that their extension is unavailable in private browsing windows.

**Comment by zombie** [comment]
We would like to keep the private browsing permission as something that extensions are not able to trigger, which only the user can manually grant, because that gives the browser more control of the process, and hopefully results in a more informed choice from the user.

Closing the issue, consensus among browser vendors is we don't want this as a feature.
