### ISSUE TITLE
WECG at TPAC 2024

### ISSUE THREAD

**Issue by xeenon** [hober/web-extensions#659]
The W3C will be holding [TPAC 2024](https://www.w3.org/2024/09/TPAC/) in Anaheim, CA, USA on September 23-27. This thread will serve as our primary discussion area for planning and scheduling purposes.

Schedule:

* Monday: 09:00 – 12:30 ([w3 calendar event](https://www.w3.org/events/meetings/f000ded1-5f74-4eb4-ac91-2328c44bb90a/))
* Tuesday: all day, switching rooms ([w3 calendar event](https://www.w3.org/events/meetings/9ded3543-e2cd-4dec-92ed-85df81ef110c/))
* Wednesday: Breakout Sessions / W3C Plenary
* Thursday: 11:00 – 12:30 ([w3 calendar event](https://www.w3.org/events/meetings/3abb0d62-fb42-4d03-847f-d57393c85607/)) and 16:30 – 18:00 ([w3 calendar event](https://www.w3.org/events/meetings/6a6be196-75d1-4a1f-95a5-bb9d37ea93dd/))
* Friday: all day, same room ([w3 calendar event](https://www.w3.org/events/meetings/ef263e93-a81e-42cb-91f6-7a75a43d94d8/))

Coordination: https://github.com/w3c/webextensions/wiki/TPAC-2024-Coordination

**Comment by dotproto** [comment]
I created the [TPAC 2024 Coordination](https://github.com/w3c/webextensions/wiki/TPAC-2024-Coordination) page on our repo's wiki to help coordinate our in-person activities.

**Comment by dotproto** [comment]
In today's meeting we briefly discussed some ides for what we should discuss or work on at TPAC. Ideas raised included:

* WebExtensions integration into Web Platform Test
  * Primary: Get tests running in Chrome, Firefox, and Safari
  * Secondary: Start building out test suites for APIs
* Check notes from San Diego F2F for topics
* Specification work
* Browser namespace
* API inconsistencies and alignment

**Comment by xeenon** [comment]
I'd like to discuss `postMessage` and possible replacement options (#77, #78).

**Comment by xeenon** [comment]
We would also like to discuss declarative cosmetic rules (#362) and plan to bring a proposal to go over.

**Comment by ameshkov** [comment]
Will there be an option to connect remotely?

**Comment by dotproto** [comment]
@ameshkov, there should be. [The TPAC site](https://www.w3.org/2024/09/TPAC/) describes the event as a hybrid meeting. [Our calendar](https://www.w3.org/groups/cg/webextensions/calendar/) on the W3C site doesn't currently have meeting info, but I'll try to make sure that those events have video conferencing info on the day of the event.

**Comment by Rob--W** [comment]
I'd like to talk about (storage) partitioning in extension APIs, including:
- #663
- `cookies.getPartitionKey` from #581
- `downloads.download` (https://bugzilla.mozilla.org/show_bug.cgi?id=1698863)
- `fetch` (https://bugzilla.mozilla.org/show_bug.cgi?id=1670278)

**Comment by hanguokai** [comment]
I won't attend this meeting. However, I suggest that in addition to specific technical issues, you can also discuss some meta issues about the ecosystem. For examples:

1. What are the biggest obstacles to browser extensions?
a) Browsers are already too complex and the development cost is high b) There is a lack of internal human resources and few external contributors.

2. Security and Privacy: Design, Permissions Models, Web Store Reviews and Enforcements.

3. Developers Success: Business Model, User Experience and Compliance Issues.

**Comment by carlosjeurissen** [comment]
1) Some of the i18n related topics which have been on the shelve for some time being:
- `i18n.getSystemUILanguage` and `i18n.getPreferredSystemLanguages`
- `i18n.getMessage` with a specified locale: https://github.com/w3c/webextensions/issues/274
- `i18n.setLanguage` and others: https://github.com/w3c/webextensions/pull/641
- `i18n.getMessage` language fallbacks https://github.com/w3c/webextensions/issues/296
- Properly formed language tags https://github.com/w3c/webextensions/issues/642

2) The issue on embedding pages we also talked about during the San Diego meeting:
https://github.com/w3c/webextensions/issues/483

3) Recently opened issue related to extension ui sizing. Discussing this during TPAC could be beneficial considering https://github.com/w3c/csswg-drafts folks being present as well:
https://github.com/w3c/webextensions/issues/692

4) Getting the associated tab id from an extension popup:
https://github.com/w3c/webextensions/issues/316#issuecomment-2078118996

5) A number of other issues we can make progress on:
https://github.com/w3c/webextensions/issues/439

@hanguokai very much agree on talking about compliance/permission models / webstore reviews and enforcement. While many of them have historically been out of scope for this group. I see a lot of value in streamlining across browsers and extension stores. We are in an awkward situation in which certain manifest files can load a browser but not accepted in a store and the reverse.
