### ISSUE TITLE
Safari 1password integration issues, maybe related to safari profiles

### ISSUE THREAD

**Issue by ardwalker** [hober/web-extensions#665]
I have issues with 1password integration. When it works it's great, but it stops responding after short while. I suspect this may be related to Safari profiles, which I make use of heavily. The problem clears when I restart Safari, but it's a real pain. Please take a look. Thanks.

**Comment by xeenon** [comment]
This would be better reported via [Feedback Assistant](feedbackassistant.apple.com), as this pertains only to Safari. Please provide Safari version and platform when reporting it. Thanks!
