### ISSUE TITLE
Proposal: Allow selection of manifest JSON when loading unpacked extensions

### ISSUE THREAD

**Issue by erosman** [hober/web-extensions#723]
# Proposal: Allow selection of manifest JSON when loading unpacked extensions

## Background

Currently, developers often have to create browser-specific (or version-specific) `manifest.json`. 
When working and/or testing on multiple browsers, developers have to rename `manifest.json` in order to load it as browsers look for that specific filename.

## Proposal
Allow developers (file-picker) to select the manifest (JSON), disregarding the filename when loading unpacked extensions

## Example

```
...
...
manifest-firefox.json
manifest-chrome.json
manifest-mv2.json
manifest-mv3.json
...
```

**Comment by xeenon** [comment]
Safari does not support loading unpacked extensions, so neutral here.

**Comment by Rob--W** [comment]
Opposed, see meeting notes for details: https://github.com/w3c/webextensions/pull/726
