### ISSUE TITLE
Specify declarativeNetRequest rules

### ISSUE THREAD

**Issue by chrmod** [hober/web-extensions#87]
As of September 2021, we have two implementations of `declarativeNetRequest` - Chrome and Safari. Sadly those  implementations are quite different. This issue focuses on the Rules only.

References:
* Chrome https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-Rule
* Safari https://developer.apple.com/documentation/safariservices/safari_web_extensions/blocking_content_with_your_safari_web_extension

Big issue for content blockers is a format in which the block rule condition should be expressed. Chrome seem to favor `urlFilter` but Safari only allows `regexFilter`. `regexFilter` on the other hand is heavily limited on Chrome to just a 1000 rules specified by MAX_NUMBER_OF_REGEX_RULES (this is likely due to poor performance of Chrome's blocking engine).

For that reason, content blockers have to generate two sets of rules sets, one for Chrome and one for Safari, which is another difference and add up to the cost extension developers have to pay due to the enforcement of `declarativeNetRequest`.

**Comment by dotproto** [comment]
Changed the title from "standardize" to "specify" as standardization is outside this group's charter. We can discuss, align on, and even produce technical reports that specify these rules, but standardization is explicitly outside our purview.

**Comment by xeenon** [comment]
Safari [does support `urlFilter`](https://github.com/WebKit/WebKit/blob/0092ec090f110aa2be240d13f771bd26edf70fec/Source/WebKit/UIProcess/Extensions/Cocoa/_WKWebExtensionDeclarativeNetRequestRule.mm#L939) now, we translate it to a regex for our implementation.
