### ISSUE TITLE
Proposal: allow to use `i18n.getMessage` in a serviceWorker

### ISSUE THREAD

**Issue by carlosjeurissen** [hober/web-extensions#93]
With mv3, `i18n.getMessage` and `i18n.getUILanguage` are not a function in the `service_worker` background script. This is troublesome as this is needed to set the label of action buttons or the entries of context menus.

One of the reasons this might not be available is the sync nature of this method. Potentially we can resolve this by either offer an promise-based initialization function for this after which `i18n.getMessage` is available. Or make an async version of `i18n.getMessage`. Using fetch calls to the _locales files is not a viable alternative as this wouldn't allow the extension developer to rely on the native browser fallback system (es_419 would fall back to es). This would also be an issue since `i18n.getUILanguage` is unavailable and one has to rely either on navigator.language(s) or `i18n.getAcceptLanguages` which both would not give the language of the browser.

See also:
- https://github.com/w3c/webextensions/issues/72#issuecomment-928425804
- [Chromium extensions group report](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/dG6JeZGkN5w)
- [Chromium bug report 1175053](https://bugs.chromium.org/p/chromium/issues/detail?id=1175053)
- [Chromium bug report 1159438](https://bugs.chromium.org/p/chromium/issues/detail?id=1159438)
- [Chromium bug report 1268098](https://bugs.chromium.org/p/chromium/issues/detail?id=1268098)

**Comment by ghostwords** [comment]
This might have gotten fixed in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1159438#c24

**Comment by carlosjeurissen** [comment]
> This might have gotten fixed in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1159438#c24

Thanks for pointing that out! It actually hasn't been fixed. `i18n.getUILanguage` is now supported, yet `i18n.getMessage` is still unavailable.

**Comment by carlosjeurissen** [comment]
Opened a new issue for it specifically for i18n.getMessage:
https://bugs.chromium.org/p/chromium/issues/detail?id=1268098

**Comment by dotproto** [comment]
Thanks for opening that issue, @carlosjeurissen. To my knowledge Chrome intends to support `i18n.getMessage()` in Manifest V3, but in order to do so we need to tweak this method to be asynchronous due to the inherently async nature of service workers.

**Comment by carlosjeurissen** [comment]
@dotproto Thanks for the update. Are there any proposals on how to do that? Potentially we can do something like `i18n.initialise('$ieft_tag')` which returns a promise which resolves when i18n.getMessage works. This would also cover https://crbug.com/660704

**Comment by maximtop** [comment]
On Chrome 103.0.5060.134 seems to be working already.

**Comment by xeenon** [comment]
I think we can close this. It was simply a bug in Chrome, and Safari has supported this in v3 since supporting v3.

**Comment by carlosjeurissen** [comment]
@xeenon Thanks for the added labels and closing the issue. Seems serviceWorkers are not yet supported in Firefox, however, this API will probably work just fine once they do.
